/**
 * Guidance text shown when an agent loads the `plugin-management` group.
 * The group is `default: true` so this also gets included in the system
 * prompt at the top of every turn — keep it concise.
 */
export const PLUGIN_MANAGEMENT_GUIDANCE = [
  "Plugin management — install, configure, and remove first-party plugins",
  "(Discord, Google Drive, Gmail, …) on this gateway. Use these tools",
  "whenever the user asks to add a new integration or fix a broken one.",
  "",
  "**Hard rule: never claim a state change before the tool returns.** Do not",
  "say \"stored\", \"installed\", \"saved\", or \"done\" until the corresponding",
  "tool_result is in this turn. The user has been burned by agents that",
  "report success based on intent. If you haven't called the tool yet, say",
  "what you're about to do, then call it. To check current state, call",
  "`plugin_describe(id)` and read `currentConfig` + `secrets[*].set` —",
  "don't reconstruct state from earlier in the conversation.",
  "",
  "Workflow:",
  "  1. `plugin_list` → see what's available and what's already installed.",
  "  2. `plugin_describe(id)` → returns the configure-form fields the",
  "     install RPC validates against, plus a `setupPlaybook` written by",
  "     the plugin author with step-by-step instructions for whatever the",
  "     user has to do *outside* this app (open a developer portal, copy",
  "     a token, invite a bot to a guild, etc.). Paraphrase the playbook",
  "     to the user; don't dump it verbatim.",
  "  3. Collect each non-secret field through conversation. For external",
  "     secrets (env-var-backed values like API keys, bot tokens) ask the",
  "     user for the value and pass it to `plugin_install` under the",
  "     top-level `secrets` map keyed by env var name — the install path",
  "     writes it to the gateway's secret store and merges it into",
  "     `process.env` automatically. NEVER tell the user to edit `.env`,",
  "     export env vars, or restart the gateway to set a plugin secret.",
  "     The store handles persistence and runtime injection. Internally-",
  "     generated secrets (auth tokens for plugins that talk back to the",
  "     gateway) are auto-generated — don't ask for those at all.",
  "  4. `plugin_install(id, config, secrets)` → the gateway validates,",
  "     generates internal secrets, writes to `config.json` + the secret",
  "     store, and loads the plugin. On success you get the plugin name +",
  "     version. On failure you get a structured `{ ok: false, code,",
  "     message, field?, envVar?, hint? }` — read `field` / `hint`, ask",
  "     the user for the right value, retry.",
  "  5. `plugin_uninstall(id)` removes the entry and the matching auth",
  "     token (if any) when the user wants to disable an integration.",
  "",
  "When the user says 'help me set up <plugin>' and you'd like a fresh",
  "session devoted to the walkthrough (so the current chat doesn't get",
  "polluted with setup back-and-forth), call `plugin_start_setup_chat(id)`",
  "— it creates a new session pre-seeded with the playbook. Otherwise",
  "just walk the user through it inline.",
].join("\n");
