import { BaseTool, type ToolContext } from "../base-tool.js";
import type { ToolExecutorResult } from "../types.js";
import type {
  PluginManagementBackend,
  PluginCatalogEntrySummary,
  PluginConfigFieldSummary,
  PluginDescribeResult,
  PluginInstallResult,
} from "./backend.js";

type AnyTool = BaseTool<Record<string, unknown>>;

/** ── plugin_list ─────────────────────────────────────────────────────── */

interface ListInput extends Record<string, unknown> {
  /** When true, only show entries the user hasn't installed yet. */
  available_only?: boolean;
}

export class PluginListTool extends BaseTool<ListInput> {
  readonly name = "plugin_list";
  readonly description = [
    "List installable / installed plugins on this gateway. Use this first",
    "when the user mentions adding/removing an integration so you know what",
    "actually exists in the catalog and what's already wired up.",
  ].join(" ");
  readonly inputSchema = {
    type: "object" as const,
    properties: {
      available_only: {
        type: "boolean",
        description:
          "When true, hide already-installed plugins (useful when the user wants suggestions).",
      },
    },
  };
  readonly tags = ["readonly", "plugin-management"] as const;

  constructor(private readonly backend: PluginManagementBackend) {
    super();
  }

  async run(input: ListInput, _ctx: ToolContext): Promise<ToolExecutorResult> {
    const entries = await this.backend.list();
    const filtered = input.available_only ? entries.filter((e) => !e.installed) : entries;
    return formatList(filtered);
  }
}

/** ── plugin_describe ─────────────────────────────────────────────────── */

interface DescribeInput extends Record<string, unknown> {
  id: string;
}

export class PluginDescribeTool extends BaseTool<DescribeInput> {
  readonly name = "plugin_describe";
  readonly description = [
    "Get the configure form for a plugin: required + optional fields, what",
    "each field means, defaults, and the author's setupPlaybook describing",
    "the steps the user has to take outside this app (e.g. opening a",
    "developer portal). Read this BEFORE calling plugin_install — the field",
    "list tells you what to collect and the playbook tells you what to walk",
    "the user through. Secrets are auto-generated; never ask the user for",
    "them.",
  ].join(" ");
  readonly inputSchema = {
    type: "object" as const,
    properties: {
      id: { type: "string", description: "Catalog id (e.g. '@squad/plugin-gmail'). Call plugin_list to discover ids." },
    },
    required: ["id"],
  };
  readonly tags = ["readonly", "plugin-management"] as const;

  constructor(private readonly backend: PluginManagementBackend) {
    super();
  }

  async run(input: DescribeInput, _ctx: ToolContext): Promise<ToolExecutorResult> {
    const desc = await this.backend.describe(input.id);
    if (!desc) throw new Error(`unknown plugin: ${input.id}`);
    return formatDescribe(desc);
  }
}

/** ── plugin_install ──────────────────────────────────────────────────── */

interface InstallInput extends Record<string, unknown> {
  id: string;
  config?: Record<string, unknown>;
  secrets?: Record<string, string>;
}

export class PluginInstallTool extends BaseTool<InstallInput> {
  readonly name = "plugin_install";
  readonly description = [
    "Install a plugin into config.json and load it. Pass three things:",
    "  - `id`: catalog id (call plugin_list to discover ids).",
    "  - `config`: non-secret schema fields the user gave you. Look at the",
    "    `fields` array from `plugin_describe` — anything WITHOUT `secret:",
    "    true` goes here.",
    "  - `secrets`: env-var-backed values (bot tokens, API keys). Look at",
    "    the `secrets` array from `plugin_describe` — for each entry whose",
    "    `set` is false, ask the user for the value and put it under its",
    "    `envVar` key here. The gateway writes these to a 0600 secrets file",
    "    and merges them into process.env. Skip entries already marked",
    "    `set: true` unless the user wants to rotate.",
    "",
    "Internally-generated secrets (auth tokens for plugins that talk back",
    "to the gateway) are auto-generated by the install path — do NOT ask",
    "for them or include them. The describe payload's `needsAuthToken`",
    "flag tells you when this applies.",
    "",
    "On success returns name + version. On failure returns a structured",
    "error with `code` (missing_config | missing_secret | import_failed |",
    "register_failed) and `field` / `envVar` / `hint` — read it, ask the",
    "user for the right value, retry.",
  ].join("\n");
  readonly inputSchema = {
    type: "object" as const,
    properties: {
      id: { type: "string", description: "Catalog id." },
      config: {
        type: "object",
        description:
          "Non-secret schema field values. Mirrors the `fields` array from plugin_describe (skip entries with `secret: true`).",
        additionalProperties: true,
      },
      secrets: {
        type: "object",
        description:
          "Env-var-backed values keyed by env var name. Mirrors the `secrets` array from plugin_describe.",
        additionalProperties: { type: "string" },
      },
    },
    required: ["id"],
  };
  readonly tags = ["write", "plugin-management"] as const;

  constructor(private readonly backend: PluginManagementBackend) {
    super();
  }

  async run(input: InstallInput, _ctx: ToolContext): Promise<ToolExecutorResult> {
    const result = await this.backend.install(
      input.id,
      input.config ?? {},
      input.secrets ?? {},
    );
    return formatInstall(result);
  }
}

/** ── plugin_uninstall ────────────────────────────────────────────────── */

interface UninstallInput extends Record<string, unknown> {
  id: string;
}

export class PluginUninstallTool extends BaseTool<UninstallInput> {
  readonly name = "plugin_uninstall";
  readonly description = [
    "Remove a plugin from config.json, drop its auth.tokens entry (if",
    "any), and unload it. Use when the user explicitly asks to remove an",
    "integration. Confirm with the user first if the plugin has stored",
    "credentials they might lose.",
  ].join(" ");
  readonly inputSchema = {
    type: "object" as const,
    properties: {
      id: { type: "string", description: "Catalog id." },
    },
    required: ["id"],
  };
  readonly tags = ["write", "plugin-management"] as const;

  constructor(private readonly backend: PluginManagementBackend) {
    super();
  }

  async run(input: UninstallInput, _ctx: ToolContext): Promise<ToolExecutorResult> {
    const result = await this.backend.uninstall(input.id);
    if (!result.ok) throw new Error(result.message ?? "uninstall failed");
    return `Uninstalled ${input.id}.`;
  }
}

/** ── plugin_start_setup_chat ─────────────────────────────────────────── */

interface SetupChatInput extends Record<string, unknown> {
  id: string;
}

export class PluginStartSetupChatTool extends BaseTool<SetupChatInput> {
  readonly name = "plugin_start_setup_chat";
  readonly description = [
    "Spin up a fresh chat session pre-seeded with this plugin's setup",
    "playbook + describe output, and return its session id. Use only when",
    "the user explicitly wants a separate session for the walkthrough —",
    "otherwise just walk them through inline. The new session has the",
    "same plugin tools available.",
  ].join(" ");
  readonly inputSchema = {
    type: "object" as const,
    properties: {
      id: { type: "string", description: "Catalog id." },
    },
    required: ["id"],
  };
  readonly tags = ["write", "plugin-management"] as const;

  constructor(private readonly backend: PluginManagementBackend) {
    super();
  }

  async run(input: SetupChatInput, _ctx: ToolContext): Promise<ToolExecutorResult> {
    const r = await this.backend.startSetupChat(input.id);
    if (!r) throw new Error(`unknown plugin: ${input.id}`);
    return `Started setup chat for ${input.id} → session ${r.sessionId}`;
  }
}

/** ── registration helper ─────────────────────────────────────────────── */

export function registerPluginManagementTools(
  registry: { register(tool: AnyTool): unknown },
  backend: PluginManagementBackend,
): void {
  registry.register(new PluginListTool(backend) as unknown as AnyTool);
  registry.register(new PluginDescribeTool(backend) as unknown as AnyTool);
  registry.register(new PluginInstallTool(backend) as unknown as AnyTool);
  registry.register(new PluginUninstallTool(backend) as unknown as AnyTool);
  registry.register(new PluginStartSetupChatTool(backend) as unknown as AnyTool);
}

// ── formatting helpers ──────────────────────────────────────────────────

function formatList(entries: PluginCatalogEntrySummary[]): string {
  if (entries.length === 0) return "(no plugins available)";
  const lines: string[] = ["Plugin catalog:"];
  for (const e of entries) {
    const state = e.error
      ? `failed (${e.error.code})`
      : e.installed
        ? e.loaded
          ? "installed"
          : "installed, not loaded"
        : "available";
    lines.push(`  - ${e.id}  [${state}]  — ${e.name}`);
    if (e.kinds.length > 0) lines.push(`    kinds: ${e.kinds.join(", ")}`);
    lines.push(`    ${e.description}`);
    if (e.error)
      lines.push(
        `    error: ${e.error.message}${e.error.field ? `  (field: ${e.error.field})` : ""}`,
      );
  }
  return lines.join("\n");
}

function formatDescribe(d: PluginDescribeResult): string {
  const lines: string[] = [
    `# ${d.name} (${d.id})`,
    "",
    d.description,
  ];
  if (d.needsAuthToken) {
    lines.push(
      "",
      "Note: install will create a matching `config.auth.tokens[]` entry so the plugin can authenticate back to this gateway. Don't ask the user for this token; it's auto-generated.",
    );
  }
  lines.push("", "## Configuration fields");
  if (d.fields.length === 0) {
    lines.push("(no configuration — install with empty config)");
  } else {
    for (const f of d.fields) {
      lines.push("", formatField(f));
    }
  }
  if (d.currentConfig) {
    lines.push(
      "",
      "## Currently saved config (secrets redacted)",
      "```json",
      JSON.stringify(d.currentConfig, null, 2),
      "```",
    );
  }
  if (d.setupPlaybook) {
    lines.push("", "## Setup playbook (paraphrase to the user)", "", d.setupPlaybook);
  }
  return lines.join("\n");
}

function formatField(f: PluginConfigFieldSummary): string {
  const tags: string[] = [f.kind];
  if (f.required && !f.secret) tags.push("required");
  if (f.secret) tags.push("secret · auto-generated");
  if (f.envRef) tags.push("env-var-name");
  const dflt =
    f.default !== undefined ? `\n  default: ${JSON.stringify(f.default)}` : "";
  const opts = f.options ? `\n  options: ${f.options.join(", ")}` : "";
  const desc = f.description ? `\n  ${f.description}` : "";
  return `- ${f.name}  [${tags.join(" · ")}]${desc}${opts}${dflt}`;
}

function formatInstall(result: PluginInstallResult): string {
  if (result.ok) {
    return `Installed ${result.name} (${result.pluginId} v${result.version}).`;
  }
  const lines = [
    `Install failed: ${result.code}`,
    `  ${result.message}`,
  ];
  if (result.field) lines.push(`  field: ${result.field}`);
  if (result.envVar) lines.push(`  env var: ${result.envVar}`);
  if (result.hint) lines.push(`  hint: ${result.hint}`);
  return lines.join("\n");
}
