import SwiftUI

// Step 2 — pair this device with the squad gateway.
// Real flow:
//   1. POST {url}/pair/begin → returns a code from the GATEWAY
//   2. App polls GET {url}/pair/poll?code=<code> until status == "approved"
//   3. Operator runs `squad pair browser <code>` on the dev box to approve
//   4. Poll returns the bearer token; we store it and switch to "paired"

struct StepConnect: View {
    let step: Int
    let total: Int
    var onPaired: (PairedSquad) -> Void
    var onBack: () -> Void

    @State private var url: String = ""
    @State private var phase: Phase = .idle
    @State private var pairing: PairingView?
    @State private var token: String?
    @State private var copied = false
    @State private var errorText: String?
    @State private var pollTask: Task<Void, Never>?

    enum Phase: Equatable { case idle, beginning, listening, paired, failed(String) }

    var body: some View {
        StepShell(
            kicker: "Step 2 · Connect",
            title: "Pair this phone with your squad.",
            sub: "Enter your squad's URL, then run the command on your dev box. The pairing code below is generated by the gateway and proves this phone is yours.",
            primary: primaryLabel,
            secondary: "Back",
            step: step, total: total,
            onPrimary: primaryAction,
            onSecondary: { pollTask?.cancel(); onBack() },
            primaryDisabled: phase == .listening || phase == .beginning || (phase == .idle && !urlValid)
        ) {
            VStack(alignment: .leading, spacing: 18) {
                urlField
                codeField
                runField
                statusBox
                if let errorText {
                    Text(errorText)
                        .font(.system(size: 12))
                        .foregroundStyle(Tokens.danger)
                }
            }
        }
    }

    // MARK: subviews

    private var urlField: some View {
        VStack(alignment: .leading, spacing: 6) {
            label("Squad URL")
            TextField("https://your-mbp.tail-scale.ts.net:8080",
                      text: $url)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .keyboardType(.URL)
                .font(Fonts.mono(13.5))
                .foregroundStyle(Tokens.fg)
                .padding(.horizontal, 14).padding(.vertical, 12)
                .background(Color.white.opacity(0.04))
                .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.white.opacity(0.08), lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: 10))
                .disabled(phase != .idle)
                .opacity(phase == .idle ? 1 : 0.6)
            Text("https://host:port (use http://ip:port for raw IPs) — default port 8080")
                .font(Fonts.mono(11))
                .foregroundStyle(Tokens.fgDim)
        }
    }

    private var codeField: some View {
        VStack(alignment: .leading, spacing: 6) {
            label("Your pairing code")
            Text(displayCode)
                .font(Fonts.mono(32, weight: .bold))
                .tracking(4)
                .foregroundStyle(Tokens.accent)
                .frame(maxWidth: .infinity)
                .padding(.vertical, 18).padding(.horizontal, 12)
                .background(LinearGradient(colors: [
                    Tokens.accent.opacity(0.12),
                    Tokens.accent.opacity(0.04),
                ], startPoint: .top, endPoint: .bottom))
                .overlay(RoundedRectangle(cornerRadius: 12).stroke(Tokens.accent.opacity(0.3), lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: 12))
            Text(codeFootnote)
                .font(Fonts.mono(11))
                .foregroundStyle(Tokens.fgDim)
        }
    }

    private var runField: some View {
        VStack(alignment: .leading, spacing: 6) {
            label("Run on your dev box")
            ZStack(alignment: .topTrailing) {
                HStack(spacing: 0) {
                    Text("$ ").font(Fonts.mono(13)).foregroundStyle(Tokens.fgDim)
                    Text(commandText)
                        .font(Fonts.mono(13))
                        .foregroundStyle(Tokens.fg)
                    Spacer()
                }
                .padding(.vertical, 12).padding(.horizontal, 14)
                .background(Color(hex: 0x0A0A0C))
                .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.white.opacity(0.06), lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: 10))
                Button {
                    UIPasteboard.general.string = commandText
                    withAnimation { copied = true }
                    Task { try? await Task.sleep(nanoseconds: 1_200_000_000); withAnimation { copied = false } }
                } label: {
                    Text(copied ? "COPIED" : "COPY")
                        .font(Fonts.mono(10, weight: .semibold))
                        .tracking(0.4)
                        .foregroundStyle(copied ? Tokens.ok : Tokens.fgDim)
                        .padding(.horizontal, 8).padding(.vertical, 4)
                        .background((copied ? Tokens.ok : Color.white).opacity(copied ? 0.16 : 0.06))
                        .overlay(RoundedRectangle(cornerRadius: 6).stroke(Color.white.opacity(0.08), lineWidth: 1))
                        .clipShape(RoundedRectangle(cornerRadius: 6))
                }
                .buttonStyle(.plain)
                .padding(8)
            }
        }
    }

    @ViewBuilder
    private var statusBox: some View {
        switch phase {
        case .listening:
            HStack(spacing: 10) {
                Pulse()
                Text("Waiting for ").font(.system(size: 12.5)).foregroundStyle(Tokens.fg)
                + Text("squad pair").font(Fonts.mono(12.5)).foregroundColor(Tokens.accent)
                + Text(" on your dev box…").font(.system(size: 12.5)).foregroundColor(Tokens.fg)
                Spacer(minLength: 0)
            }
            .padding(.horizontal, 12).padding(.vertical, 11)
            .background(Tokens.accent.opacity(0.08))
            .overlay(RoundedRectangle(cornerRadius: 10).stroke(Tokens.accent.opacity(0.25), lineWidth: 1))
            .clipShape(RoundedRectangle(cornerRadius: 10))
        case .paired:
            HStack(spacing: 10) {
                Image(systemName: "checkmark.circle.fill").foregroundStyle(Tokens.ok)
                Text("Paired with this squad")
                    .font(.system(size: 13)).foregroundStyle(Tokens.ok)
                Spacer()
            }
            .padding(.horizontal, 12).padding(.vertical, 11)
            .background(Tokens.ok.opacity(0.08))
            .overlay(RoundedRectangle(cornerRadius: 10).stroke(Tokens.ok.opacity(0.25), lineWidth: 1))
            .clipShape(RoundedRectangle(cornerRadius: 10))
        case .idle, .beginning:
            HStack(alignment: .top, spacing: 10) {
                Image(systemName: "lock.shield")
                    .foregroundStyle(Tokens.fgMuted)
                    .font(.system(size: 14))
                    .padding(.top, 1)
                Text("The code proves this phone owns the connection. Once paired, the squad stores a long-lived token — revoke devices anytime with `squad pair browser cancel`.")
                    .font(.system(size: 12.5))
                    .foregroundStyle(Tokens.fgMuted)
                Spacer(minLength: 0)
            }
            .padding(.horizontal, 12).padding(.vertical, 11)
            .background(Color.white.opacity(0.03))
            .overlay(RoundedRectangle(cornerRadius: 10).stroke(Color.white.opacity(0.06), lineWidth: 1))
            .clipShape(RoundedRectangle(cornerRadius: 10))
        case .failed(let msg):
            HStack(alignment: .top, spacing: 10) {
                Image(systemName: "exclamationmark.triangle")
                    .foregroundStyle(Tokens.danger).padding(.top, 1)
                Text(msg).font(.system(size: 12.5)).foregroundStyle(Tokens.danger)
                Spacer(minLength: 0)
            }
            .padding(.horizontal, 12).padding(.vertical, 11)
            .background(Tokens.danger.opacity(0.08))
            .overlay(RoundedRectangle(cornerRadius: 10).stroke(Tokens.danger.opacity(0.25), lineWidth: 1))
            .clipShape(RoundedRectangle(cornerRadius: 10))
        }
    }

    private func label(_ text: String) -> some View {
        Text(text.uppercased())
            .font(Fonts.mono(10, weight: .bold))
            .tracking(1.2)
            .foregroundStyle(Tokens.fgDim)
    }

    // MARK: derived

    private var primaryLabel: String {
        switch phase {
        case .paired: "Continue"
        case .listening: "Waiting…"
        case .beginning: "Starting…"
        case .idle, .failed: "Start pairing"
        }
    }
    private var displayCode: String {
        if let c = pairing?.code { return c }
        return "— — —"
    }
    private var codeFootnote: String {
        if let p = pairing { return "issued by gateway · expires at \(p.expiresAt ?? "—")" }
        return "the gateway issues this once you press Start pairing"
    }
    private var commandText: String {
        if let c = pairing?.code { return "squad pair browser \(c)" }
        return "squad pair browser <CODE>"
    }
    private var urlValid: Bool { url.trimmingCharacters(in: .whitespaces).count >= 7 }

    // MARK: actions

    private func primaryAction() {
        switch phase {
        case .paired:
            pollTask?.cancel()
            if let token, let pairing {
                let normalized = url.trimmingCharacters(in: .whitespaces)
                let p = PairedSquad(
                    name: pairing.label ?? "squad",
                    url: normalized,
                    token: token,
                    pairedAt: Date()
                )
                onPaired(p)
            }
        case .idle, .failed:
            beginPairing()
        case .listening, .beginning:
            break
        }
    }

    private func beginPairing() {
        let baseURL = url.trimmingCharacters(in: .whitespaces)
        guard !baseURL.isEmpty else { return }
        errorText = nil
        phase = .beginning
        Task {
            do {
                let begin = try await SquadHTTP.postJSON(
                    baseURL, path: "/pair/begin",
                    body: ["label": "Squad Mobile (iOS)"],
                    as: PairingBegin.self
                )
                self.pairing = begin.pairing
                self.phase = .listening
                self.startPolling(baseURL: baseURL, code: begin.pairing.code)
            } catch {
                self.phase = .failed("couldn't reach \(baseURL): \(error.localizedDescription)")
            }
        }
    }

    private func startPolling(baseURL: String, code: String) {
        pollTask?.cancel()
        pollTask = Task {
            // Poll every 1.5s for up to ~5 minutes.
            let started = Date()
            while !Task.isCancelled, Date().timeIntervalSince(started) < 5 * 60 {
                do {
                    let r = try await SquadHTTP.getJSON(baseURL, path: "/pair/poll",
                                                       query: ["code": code], as: PairingPoll.self)
                    switch r.status {
                    case "approved":
                        if let token = r.token {
                            self.token = token
                            self.phase = .paired
                            return
                        }
                    case "expired", "cancelled":
                        self.phase = .failed("pairing \(r.status)")
                        return
                    default:
                        break // pending or claimed — keep polling
                    }
                } catch {
                    // transient — keep retrying until the timeout
                }
                try? await Task.sleep(nanoseconds: 1_500_000_000)
            }
            if !Task.isCancelled, self.phase == .listening {
                self.phase = .failed("pairing timed out — try again")
            }
        }
    }
}
