// Back-compat re-export. Rich renderers live in ./ui/render.ts.
export {
  renderDelta,
  renderNewline,
  renderAssistantMessage,
  renderUserLine,
  renderToolCall,
  renderToolCallStart,
  renderToolResult,
  renderTaskList,
  renderAskPrompt,
  renderError,
  renderInfo,
  renderSuccess,
  renderWarn,
  renderHeader,
  renderRule,
  renderDim,
  renderKeyValue,
  endDeltaBlock,
  type VerboseLevel,
} from "./ui/render.js";
