import { spawn, execSync } from "node:child_process";
import {
  chmodSync,
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { randomBytes } from "node:crypto";

import {
  COMPOSE_PATH,
  CURRENT_FILE,
  SHARED_DIR,
  SQUAD_HOME,
  squadConfigPath,
  squadDataDir,
  squadDir,
  squadEnvPath,
} from "../mgr/paths.js";
import {
  findFreePort,
  getSquad,
  loadRegistry,
  requireSquad,
  saveRegistry,
  validateName,
  type Registry,
  type Squad,
} from "../mgr/registry.js";
import { generateCompose } from "../mgr/compose-gen.js";
import { isRunning, listRunningSquads } from "../mgr/discovery.js";
import * as render from "../render.js";
import { C, color, fg } from "../ui/colors.js";
import { roleColor } from "../ui/skin.js";

// ─── repo location (for build context + import) ────────────────────────────

function findRepoRoot(): string {
  let dir = resolve(process.env.SQUAD_REPO ?? import.meta.dirname ?? process.cwd());
  while (true) {
    if (existsSync(join(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(
        "can't locate the squad source repo. Set SQUAD_REPO=/path/to/squad-source.",
      );
    }
    dir = parent;
  }
}

function ensureRepo(reg: Registry): Registry {
  if (reg.build_context && existsSync(reg.build_context)) return reg;
  const root = findRepoRoot();
  return { ...reg, build_context: root };
}

// ─── docker compose plumbing ───────────────────────────────────────────────

function composeCmd(): string[] {
  try {
    execSync("docker compose version", { stdio: "ignore" });
    return ["docker", "compose"];
  } catch {
    // legacy v1
    return ["docker-compose"];
  }
}

async function runComposeAsync(
  args: string[],
  opts: { stdio?: "inherit" | "pipe" } = {},
): Promise<number> {
  const [bin, ...rest] = composeCmd();
  const argv = [...rest, "-f", COMPOSE_PATH, ...args];
  return new Promise((resolveP) => {
    const child = spawn(bin!, argv, { stdio: opts.stdio ?? "inherit", cwd: SQUAD_HOME });
    child.on("exit", (code) => resolveP(code ?? 0));
  });
}

// ─── scaffolding ───────────────────────────────────────────────────────────

function generateToken(bytes = 32): string {
  return randomBytes(bytes).toString("base64url");
}

function ensureSquadHome(): void {
  if (!existsSync(SQUAD_HOME)) mkdirSync(SQUAD_HOME, { recursive: true });
  if (!existsSync(SHARED_DIR)) mkdirSync(SHARED_DIR, { recursive: true });
}

const DEFAULT_CONFIG_TEMPLATE = {
  $comment:
    "Generated by 'squad mgr create'. Hand-edit freely — mgr does not rewrite it.",
  server: {
    host: "0.0.0.0",
    data_dir: "/app/docker/data",
    port: 8080,
  },
  auth: {
    tokens: [
      { label: "dashboard", key_env: "SQUAD_DASHBOARD_TOKEN", scopes: ["*"] },
    ],
  },
  chat: { delivery: "interrupt" },
  llm: {
    primary: { model: "anthropic/claude-sonnet-4-5" },
    fallbacks: [],
    providers: { anthropic: { api_key_env: "ANTHROPIC_API_KEY" } },
  },
  subagents: {
    max_concurrent_global: 8,
    max_concurrent_per_parent: 4,
    max_tree_depth: 3,
  },
  policy: {
    approvals: {
      default: "tag-match",
      require_for_tags: ["write", "exec", "network"],
      timeout_seconds: 120,
    },
  },
  plugins: [],
};

function scaffoldSquad(name: string, opts: { copyFromConfig?: string; copyFromEnv?: string }): void {
  const dir = squadDir(name);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(squadDataDir(name))) mkdirSync(squadDataDir(name), { recursive: true });
  const sshDir = join(dir, "data", "ssh");
  if (!existsSync(sshDir)) mkdirSync(sshDir, { recursive: true, mode: 0o700 });

  const cfgPath = squadConfigPath(name);
  if (!existsSync(cfgPath)) {
    if (opts.copyFromConfig && existsSync(opts.copyFromConfig)) {
      copyFileSync(opts.copyFromConfig, cfgPath);
    } else {
      writeFileSync(cfgPath, JSON.stringify(DEFAULT_CONFIG_TEMPLATE, null, 2) + "\n");
    }
  }

  const envPath = squadEnvPath(name);
  if (!existsSync(envPath)) {
    let body: string;
    if (opts.copyFromEnv && existsSync(opts.copyFromEnv)) {
      body = readFileSync(opts.copyFromEnv, "utf8");
      // Always rotate the dashboard token when cloning so two squads don't
      // share the same WS auth secret.
      body = upsertEnvLine(body, "SQUAD_DASHBOARD_TOKEN", generateToken());
    } else {
      body = renderDefaultEnv();
    }
    writeFileSync(envPath, body);
    try {
      chmodSync(envPath, 0o600);
    } catch {
      // best-effort on Windows
    }
  }
}

function renderDefaultEnv(): string {
  return [
    "# Generated by 'squad mgr create'. Holds secrets — do not commit.",
    "",
    "# --- dashboard / WS auth ---",
    `SQUAD_DASHBOARD_TOKEN=${generateToken()}`,
    "",
    "# --- LLM provider keys (uncomment + fill what you use) ---",
    "# ANTHROPIC_API_KEY=",
    "# OPENAI_API_KEY=",
    "# OPENROUTER_API_KEY=",
    "",
    "# --- Git identity (used by container for commits) ---",
    "# GIT_USER_NAME=",
    "# GIT_USER_EMAIL=",
    "# GITHUB_TOKEN=",
    "",
    "# --- Discord (one bot per squad — separate token) ---",
    "# DISCORD_BOT_TOKEN=",
    "# SQUAD_DISCORD_TOKEN=",
    "",
  ].join("\n");
}

function upsertEnvLine(body: string, key: string, value: string): string {
  const lines = body.split(/\r?\n/);
  let found = false;
  const out = lines.map((line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith("#")) return line;
    const eq = trimmed.indexOf("=");
    if (eq === -1) return line;
    if (trimmed.slice(0, eq).trim() !== key) return line;
    found = true;
    return `${key}=${value}`;
  });
  if (!found) out.push(`${key}=${value}`);
  return out.join("\n");
}

// ─── compose regen ─────────────────────────────────────────────────────────

function regenCompose(reg: Registry): void {
  ensureSquadHome();
  // Make sure the shared searxng settings dir exists so the bind mount works
  // even if the user hasn't configured anything yet.
  const searxngDir = join(SHARED_DIR, "searxng");
  if (!existsSync(searxngDir)) mkdirSync(searxngDir, { recursive: true });
  writeFileSync(COMPOSE_PATH, generateCompose(reg));
}

// ─── subcommands ───────────────────────────────────────────────────────────

const muted = () => fg(roleColor("muted"));
const ok = () => fg(roleColor("ok"));
const warn = () => fg(roleColor("warn"));
const errC = () => fg(roleColor("err"));

function popFlag(args: string[], name: string): string | undefined {
  const i = args.indexOf(name);
  if (i === -1) return undefined;
  const val = args[i + 1];
  args.splice(i, 2);
  return val;
}

function hasFlag(args: string[], name: string): boolean {
  const i = args.indexOf(name);
  if (i === -1) return false;
  args.splice(i, 1);
  return true;
}

async function cmdCreate(args: string[]): Promise<void> {
  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr create <name> [--port N] [--from <name>]");
  validateName(name);

  let reg = loadRegistry();
  reg = ensureRepo(reg);
  if (getSquad(reg, name)) throw new Error(`squad '${name}' already exists`);

  const portArg = popFlag(args, "--port");
  const port = portArg ? Number(portArg) : findFreePort(reg, 8080);
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(`invalid port: ${portArg}`);
  }
  if (reg.squads.some((s) => s.port === port)) {
    throw new Error(`port ${port} already used by squad '${reg.squads.find((s) => s.port === port)!.name}'`);
  }

  const fromName = popFlag(args, "--from");
  let copyFromConfig: string | undefined;
  let copyFromEnv: string | undefined;
  if (fromName) {
    const src = requireSquad(reg, fromName);
    copyFromConfig = squadConfigPath(src.name);
    copyFromEnv = squadEnvPath(src.name);
  }

  scaffoldSquad(name, {
    ...(copyFromConfig ? { copyFromConfig } : {}),
    ...(copyFromEnv ? { copyFromEnv } : {}),
  });

  reg.squads.push({ name, port });
  saveRegistry(reg);
  regenCompose(reg);

  const home = squadDir(name);
  process.stdout.write(
    `${color("✓", ok())} created squad '${name}' on port ${port}\n` +
      `  state:  ${home}\n` +
      `  config: ${squadConfigPath(name)}\n` +
      `  env:    ${squadEnvPath(name)}    ${color("← add API keys here", muted())}\n` +
      `  start:  ${color(`squad mgr start ${name}`, muted())}\n`,
  );
}

async function cmdRm(args: string[]): Promise<void> {
  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr rm <name> [--purge]");
  const purge = hasFlag(args, "--purge");

  const reg = loadRegistry();
  requireSquad(reg, name);

  // Stop + remove the container if it exists. Tolerate failure (already gone).
  if (existsSync(COMPOSE_PATH)) {
    await runComposeAsync(["rm", "-sf", `squad-${name}`]);
  }

  const next = { ...reg, squads: reg.squads.filter((s) => s.name !== name) };
  saveRegistry(next);
  regenCompose(next);

  // Clear current pointer if it pointed here.
  if (existsSync(CURRENT_FILE) && readFileSync(CURRENT_FILE, "utf8").trim() === name) {
    unlinkSync(CURRENT_FILE);
  }

  if (purge) {
    rmSync(squadDir(name), { recursive: true, force: true });
    process.stdout.write(`${color("✓", ok())} removed squad '${name}' and wiped ${squadDir(name)}\n`);
  } else {
    process.stdout.write(
      `${color("✓", ok())} removed squad '${name}' from registry\n` +
        `  state preserved at ${squadDir(name)}  ${color("(re-add with: squad mgr import " + name + ")", muted())}\n`,
    );
  }
}

async function cmdLs(_args: string[]): Promise<void> {
  const reg = loadRegistry();
  const running = listRunningSquads();
  const runMap = new Map(running.map((r) => [r.name, r]));

  if (reg.squads.length === 0 && running.length === 0) {
    process.stdout.write(`no squads registered. ${color("squad mgr create <name>", muted())}\n`);
    return;
  }

  // Union: registry entries + any running container not in registry (drift).
  const allNames = new Set<string>();
  for (const s of reg.squads) allNames.add(s.name);
  for (const r of running) allNames.add(r.name);

  const current = existsSync(CURRENT_FILE) ? readFileSync(CURRENT_FILE, "utf8").trim() : "";

  const rows: Array<[string, string, string, string]> = [
    ["NAME", "PORT", "STATUS", ""],
  ];
  for (const name of [...allNames].sort()) {
    const s = getSquad(reg, name);
    const r = runMap.get(name);
    const port = String(s?.port ?? r?.port ?? "?");
    let status: string;
    if (r) {
      status = isRunning(r.status)
        ? color(r.health || "running", ok())
        : color("stopped", muted());
    } else {
      status = color("not started", muted());
    }
    const tag = name === current ? color("← current", warn()) : "";
    if (!s) status = color("(unregistered)", warn()) + " " + status;
    rows.push([name, port, status, tag]);
  }
  for (const [a, b, c, d] of rows) {
    process.stdout.write(`  ${a.padEnd(20)} ${b.padEnd(8)} ${c.padEnd(24)} ${d}\n`);
  }
}

async function cmdStart(args: string[]): Promise<void> {
  const reg = ensureRepo(loadRegistry());
  // Always regen first so config edits in squads.json land before docker reads it.
  regenCompose(reg);

  if (hasFlag(args, "--all")) {
    const services = reg.squads.map((s) => `squad-${s.name}`);
    if (services.length === 0) throw new Error("no squads registered");
    services.push("searxng");
    const code = await runComposeAsync(["up", "-d", "--build", ...services]);
    process.exitCode = code;
    return;
  }

  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr start <name>|--all");
  requireSquad(reg, name);
  const code = await runComposeAsync(["up", "-d", "--build", `squad-${name}`]);
  process.exitCode = code;
}

async function cmdStop(args: string[]): Promise<void> {
  if (!existsSync(COMPOSE_PATH)) {
    process.stdout.write("no compose file — nothing to stop.\n");
    return;
  }
  if (hasFlag(args, "--all")) {
    const code = await runComposeAsync(["down"]);
    process.exitCode = code;
    return;
  }
  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr stop <name>|--all");
  const code = await runComposeAsync(["stop", `squad-${name}`]);
  process.exitCode = code;
}

async function cmdRestart(args: string[]): Promise<void> {
  const reg = ensureRepo(loadRegistry());

  if (hasFlag(args, "--all")) {
    if (reg.squads.length === 0) throw new Error("no squads registered");
    regenCompose(reg);
    if (existsSync(COMPOSE_PATH)) {
      const stopCode = await runComposeAsync(["down"]);
      if (stopCode !== 0) {
        process.exitCode = stopCode;
        return;
      }
    }
    const services = reg.squads.map((s) => `squad-${s.name}`);
    services.push("searxng");
    const code = await runComposeAsync(["up", "-d", "--build", ...services]);
    process.exitCode = code;
    return;
  }

  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr restart <name>|--all");
  requireSquad(reg, name);
  regenCompose(reg);
  const code = await runComposeAsync(["restart", `squad-${name}`]);
  process.exitCode = code;
}

async function cmdLogs(args: string[]): Promise<void> {
  const follow = hasFlag(args, "-f") || hasFlag(args, "--follow");
  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr logs <name> [-f]");
  const code = await runComposeAsync(
    ["logs", ...(follow ? ["-f"] : []), `squad-${name}`],
  );
  process.exitCode = code;
}

async function cmdUse(args: string[]): Promise<void> {
  const name = args.shift();
  if (!name) {
    if (existsSync(CURRENT_FILE)) {
      process.stdout.write(readFileSync(CURRENT_FILE, "utf8").trim() + "\n");
    }
    return;
  }
  const reg = loadRegistry();
  requireSquad(reg, name);
  ensureSquadHome();
  writeFileSync(CURRENT_FILE, name + "\n");
  process.stdout.write(`${color("✓", ok())} current squad set to '${name}'\n`);
}

async function cmdRegen(_args: string[]): Promise<void> {
  const reg = ensureRepo(loadRegistry());
  saveRegistry(reg); // persist the build_context if it was just discovered
  regenCompose(reg);
  process.stdout.write(`${color("✓", ok())} wrote ${COMPOSE_PATH}\n`);
}

async function cmdImport(args: string[]): Promise<void> {
  // Re-register an existing ~/.squad/squads/<name>/ directory that was
  // previously removed from squads.json (e.g. via `squad mgr rm`).
  const name = args.shift();
  if (!name) throw new Error("usage: squad mgr import <name>");
  const reg = ensureRepo(loadRegistry());
  validateName(name);
  if (getSquad(reg, name)) throw new Error(`squad '${name}' already in registry`);
  const dir = squadDir(name);
  if (!existsSync(dir)) throw new Error(`no directory at ${dir}`);
  const port = findFreePort(reg);
  reg.squads.push({ name, port });
  saveRegistry(reg);
  regenCompose(reg);
  process.stdout.write(`${color("✓", ok())} re-registered '${name}' on port ${port}\n`);
}

async function cmdExec(args: string[]): Promise<void> {
  const all = hasFlag(args, "--all");
  const target = popFlag(args, "--squad");
  if (!args.length) throw new Error("usage: squad mgr exec <cmd ...> [--squad <name>|--all]");

  const reg = loadRegistry();
  const targets: string[] = all ? reg.squads.map((s) => s.name) : target ? [target] : [];
  if (targets.length === 0) throw new Error("specify --squad <name> or --all");

  const self = process.argv[1] ?? "squad";
  for (const name of targets) {
    process.stdout.write(`${color(`── ${name} ──`, muted())}\n`);
    await new Promise<void>((resolveP) => {
      const child = spawn(process.execPath, [self, ...args], {
        stdio: "inherit",
        env: { ...process.env, SQUAD_NAME: name },
      });
      child.on("exit", () => resolveP());
    });
  }
}

function helpText(): string {
  const accent = fg(roleColor("accent"));
  const K = (s: string) => `${fg(roleColor("brand"))}${s}${C.RESET}`;
  const D = (s: string) => `${muted()}${s}${C.RESET}`;
  const H = (s: string) => `${C.BOLD}${accent}${s}${C.RESET}`;
  return [
    "",
    `  ${H("Usage")}  ${K("squad mgr")} ${D("<subcommand> [args]")}`,
    "",
    `  ${H("Lifecycle")}`,
    `    ${K("create")} ${D("<name> [--port N] [--from <name>]")}  ${D("scaffold ~/.squad/squads/<name>/, register, regen compose")}`,
    `    ${K("rm")}     ${D("<name> [--purge]")}                    ${D("stop, unregister; --purge wipes state dir")}`,
    `    ${K("ls")}                                       ${D("list squads + running status (via docker labels)")}`,
    `    ${K("start")}  ${D("<name>|--all")}                        ${D("docker compose up -d")}`,
    `    ${K("stop")}   ${D("<name>|--all")}                        ${D("docker compose stop / down")}`,
    `    ${K("restart")} ${D("<name>|--all")}                       ${D("in-place restart; --all does full stop + up --build")}`,
    `    ${K("logs")}   ${D("<name> [-f]")}                         ${D("docker compose logs")}`,
    "",
    `  ${H("Selection")}`,
    `    ${K("use")} ${D("[<name>]")}                              ${D("set/show the active squad (~/.squad/current)")}`,
    "",
    `  ${H("Maintenance")}`,
    `    ${K("regen")}                                    ${D("rewrite ~/.squad/docker-compose.yml from squads.json")}`,
    `    ${K("import")} ${D("<name>")}                              ${D("re-register an existing ~/.squad/squads/<name>/ directory")}`,
    `    ${K("exec")} ${D("<cmd ...> --squad <name>|--all")}       ${D("run another squad CLI command against one or all squads")}`,
    "",
    `  ${H("State layout")}`,
    `    ${D("~/.squad/squads.json            registry (source of truth)")}`,
    `    ${D("~/.squad/docker-compose.yml     generated; never hand-edit")}`,
    `    ${D("~/.squad/<name>/                per-squad config + .env + data + ssh")}`,
    `    ${D("~/.squad/shared/searxng/        shared local search settings")}`,
    `    ${D("~/.squad/extensions/            optional shared plugin dir (mounted ro)")}`,
    "",
  ].join("\n");
}

export async function runMgr(args: string[]): Promise<void> {
  const sub = args.shift();
  if (!sub || sub === "help" || sub === "--help" || sub === "-h") {
    process.stdout.write(helpText());
    return;
  }
  switch (sub) {
    case "create":
      return cmdCreate(args);
    case "rm":
    case "remove":
    case "delete":
      return cmdRm(args);
    case "ls":
    case "list":
      return cmdLs(args);
    case "start":
      return cmdStart(args);
    case "stop":
      return cmdStop(args);
    case "restart":
      return cmdRestart(args);
    case "logs":
      return cmdLogs(args);
    case "use":
      return cmdUse(args);
    case "regen":
      return cmdRegen(args);
    case "import":
      return cmdImport(args);
    case "exec":
      return cmdExec(args);
    default:
      render.renderError(`unknown: squad mgr ${sub}`);
      process.stderr.write(helpText());
      process.exitCode = 2;
  }
}

