import type { Registry, Squad } from "./registry.js";
import { existsSync } from "node:fs";
import { EXTENSIONS_DIR, SHARED_DIR, squadDir } from "./paths.js";

const HEADER = `# GENERATED by 'squad mgr regen' — do not edit by hand.
# Source of truth: ~/.squad/squads.json
# To add or remove a squad: 'squad mgr create <name>' / 'squad mgr rm <name>'.
`;

/**
 * Render the multi-squad docker-compose.yml. Each squad gets its own service
 * named squad-<name>, sharing one searxng sidecar. Bind mounts use absolute
 * host paths (compose runs from ~/.squad, but absolute paths are always
 * unambiguous).
 *
 * Pure function: takes the registry, returns the full file content.
 */
export function generateCompose(reg: Registry): string {
  if (!reg.build_context) {
    throw new Error("registry.build_context is empty — pass it via mgr regen");
  }

  const services: string[] = [];
  for (const squad of reg.squads) {
    services.push(renderSquadService(squad, reg.build_context));
  }
  services.push(renderSearxngService(reg.shared.searxng_port));

  return `${HEADER}
services:
${services.join("\n")}`;
}

function renderSquadService(squad: Squad, buildContext: string): string {
  const sd = squadDir(squad.name);
  const extensionsMount = existsSync(EXTENSIONS_DIR)
    ? `      - ${EXTENSIONS_DIR}:/app/extensions:ro\n`
    : "";
  // The container always listens on 8080 internally — keeping that constant
  // means per-squad config.json doesn't need to be rewritten when the host
  // port changes, and the in-process Discord plugin's default
  // ws://127.0.0.1:8080/ws keeps working unchanged.
  return `  squad-${squad.name}:
    build:
      context: ${buildContext}
      dockerfile: Dockerfile
    container_name: squad-${squad.name}
    ports:
      - "${squad.port}:8080"
    env_file:
      - ${sd}/.env
    environment:
      - SQUAD_CONFIG=/app/docker/config.json
      - SEARXNG_URL=http://searxng:8080
      # Tells the gateway that Docker (via 'restart: unless-stopped') will
      # respawn this container on exit. The agent's restart_gateway tool keys
      # off this to know the restart will actually complete.
      - SQUAD_RESTART_POLICY=docker
    volumes:
      - ${sd}:/app/docker
${extensionsMount}    depends_on:
      searxng:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - lobs.squad.name=${squad.name}
      - lobs.squad.port=${squad.port}
    restart: unless-stopped
`;
}

function renderSearxngService(port: number): string {
  return `  searxng:
    image: searxng/searxng:latest
    container_name: squad-searxng
    ports:
      - "${port}:8080"
    environment:
      - BASE_URL=http://localhost:${port}/
      - INSTANCE_NAME=squad-searxng
    volumes:
      - ${SHARED_DIR}/searxng:/etc/searxng:rw
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O- http://localhost:8080/search?q=ping&format=json >/dev/null 2>&1 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - lobs.squad.shared=searxng
    restart: unless-stopped
`;
}
