import type { Registry, Squad } from "./registry.js";
import { existsSync } from "node:fs";
import { EXTENSIONS_DIR, SHARED_DIR, squadDir } from "./paths.js";

const HEADER = `# GENERATED by 'squad mgr regen' — do not edit by hand.
# Source of truth: ~/.squad/squads.json
# To add or remove a squad: 'squad mgr create <name>' / 'squad mgr rm <name>'.
`;

/**
 * Render the multi-squad docker-compose.yml. Each squad gets its own service
 * named squad-<name>, sharing one searxng sidecar. Bind mounts use absolute
 * host paths (compose runs from ~/.squad, but absolute paths are always
 * unambiguous).
 *
 * Pure function: takes the registry, returns the full file content.
 */
export function generateCompose(reg: Registry): string {
  if (!reg.build_context) {
    throw new Error("registry.build_context is empty — pass it via mgr regen");
  }

  const services: string[] = [];
  for (const squad of reg.squads) {
    services.push(renderSquadService(squad, reg.build_context));
  }
  services.push(renderSearxngService(reg.shared.searxng_port));
  services.push(renderPostgresService());
  services.push(renderRedisService());

  // Explicit project name so every container in this file groups under
  // "squad" in Docker Desktop, regardless of the directory the compose file
  // is invoked from.
  return `${HEADER}
name: squad

services:
${services.join("\n")}

volumes:
  squad_pgdata:
  squad_redisdata:
`;
}

function renderSquadService(squad: Squad, buildContext: string): string {
  const sd = squadDir(squad.name);
  const extensionsMount = existsSync(EXTENSIONS_DIR)
    ? `      - ${EXTENSIONS_DIR}:/app/extensions:ro\n`
    : "";
  // The container always listens on 8080 internally — keeping that constant
  // means per-squad config.json doesn't need to be rewritten when the host
  // port changes, and the in-process Discord plugin's default
  // ws://127.0.0.1:8080/ws keeps working unchanged.
  return `  squad-${squad.name}:
    build:
      context: ${buildContext}
      dockerfile: Dockerfile
    container_name: squad-${squad.name}
    ports:
      - "${squad.port}:8080"
    env_file:
      - ${sd}/.env
    environment:
      - SQUAD_CONFIG=/app/docker/config.json
      - SEARXNG_URL=http://searxng:8080
      # Tells the gateway that Docker (via 'restart: unless-stopped') will
      # respawn this container on exit. The agent's restart_gateway tool keys
      # off this to know the restart will actually complete.
      - SQUAD_RESTART_POLICY=docker
    volumes:
      - ${sd}:/app/docker
${extensionsMount}    # Lets the container reach services bound to the host's loopback (Ollama,
    # LM Studio, vLLM, etc.) via http://host.docker.internal:<port>. Docker
    # Desktop wires this automatically; the host-gateway alias makes the same
    # compose work on Linux too.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      searxng:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    labels:
      - lobs.squad.name=${squad.name}
      - lobs.squad.port=${squad.port}
    restart: unless-stopped
`;
}

function renderPostgresService(): string {
  // pgvector image so MemCore's vector ops work out of the box. No host port
  // exposure: squad services reach it via the in-network hostname `postgres`.
  // Bind 127.0.0.1:5433 so a host-side psql / migration tool still works
  // alongside any system Postgres on 5432.
  return `  postgres:
    image: pgvector/pgvector:pg16
    container_name: squad-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memcore
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - squad_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d memcore"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - lobs.squad.shared=postgres
    restart: unless-stopped
`;
}

function renderRedisService(): string {
  return `  redis:
    image: redis:7-alpine
    container_name: squad-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - squad_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    labels:
      - lobs.squad.shared=redis
    restart: unless-stopped
`;
}

function renderSearxngService(port: number): string {
  return `  searxng:
    image: searxng/searxng:latest
    container_name: squad-searxng
    ports:
      - "${port}:8080"
    environment:
      - BASE_URL=http://localhost:${port}/
      - INSTANCE_NAME=squad-searxng
    volumes:
      - ${SHARED_DIR}/searxng:/etc/searxng:rw
    healthcheck:
      test:
        - CMD-SHELL
        - "wget -q -O- http://localhost:8080/search?q=ping&format=json >/dev/null 2>&1 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    labels:
      - lobs.squad.shared=searxng
    restart: unless-stopped
`;
}
