export const GMAIL_GUIDANCE = [
  "Gmail — search, read, send, and label email through the connected Google account.",
  "Operates against the first connected account with the `gmail` feature enabled. Use",
  "google_list_accounts to confirm an account is connected before calling these tools.",
  "",
  "Tools in this group:",
  "  - gmail_search        → Gmail-syntax query (`from:`, `subject:`, `newer_than:`, etc.). Returns ids + snippets.",
  "  - gmail_read          → fetch a full message by id; returns headers, labels, and the text or html body.",
  "  - gmail_send          → send an email; supports threading via reply_to_message_id and cc/bcc lists.",
  "  - gmail_modify_labels → add and/or remove labels on a message id.",
  "  - gmail_list_labels   → enumerate built-in + user labels, with their ids.",
  "",
  "Conventions:",
  "  - Gmail query syntax beats keyword matching — `from:alice subject:invoice newer_than:7d` works.",
  "  - System labels are upper-case strings: INBOX, UNREAD, STARRED, IMPORTANT, TRASH, SPAM.",
  "  - Custom labels need their LabelId (not the human label name) — fetch via gmail_list_labels.",
  "  - gmail_send threads correctly when you pass reply_to_message_id; the subject auto-prefixes 'Re:'.",
  "  - Bodies are plain text; the tool sets MIME headers for you.",
  "",
  "Common patterns:",
  "  - 'find unread invoices':         gmail_search query='is:unread subject:invoice'.",
  "  - 'show me message X':            gmail_read message_id=...; pass body_format=html for HTML mail.",
  "  - 'reply to that email':          gmail_send to=..., reply_to_message_id=...",
  "  - 'archive that thread':          gmail_modify_labels remove_labels=['INBOX'].",
  "  - 'mark as read':                 gmail_modify_labels remove_labels=['UNREAD'].",
].join("\n");
