export const GOOGLE_AUTH_GUIDANCE = [
  "Google account management — list connected Google accounts, get a connect URL, or disconnect.",
  "These tools are the entry point before any calendar / gmail / drive call: they expose which",
  "account ids exist, which features (calendar/gmail/drive) each has enabled, and where to send",
  "the user to bring a new account online.",
  "",
  "Tools in this group:",
  "  - google_list_accounts       → list connected accounts with their email + features.",
  "  - google_connect_url         → return a URL the user opens in their browser to OAuth a new account.",
  "  - google_disconnect_account  → revoke tokens and remove an account by id.",
  "",
  "Workflow:",
  "  1. Call google_list_accounts to see what is connected.",
  "  2. If nothing is connected (or the needed feature isn't enabled), call google_connect_url",
  "     and hand the URL to the user — do not try to follow the OAuth flow yourself.",
  "  3. Once an account is connected, the calendar / gmail / drive tool groups become usable.",
  "",
  "Account ids look like `ga_xxxxxxxxxxxx`. Disconnect both revokes the OAuth tokens upstream and",
  "drops the row locally — irreversible without re-consenting.",
].join("\n");
