export const GOOGLE_AUTH_GUIDANCE = [
  "Google account management — list connected Google accounts, get a connect URL, or disconnect.",
  "These tools are the entry point before any calendar / gmail / drive call: they expose which",
  "account ids exist, which features (calendar/gmail/drive) each has enabled, and where to send",
  "the user to bring a new account online.",
  "",
  "Tools in this group:",
  "  - google_list_accounts       → list connected accounts with their email + features.",
  "  - google_connect_url         → return a URL the user opens in their browser to OAuth a new account.",
  "  - google_disconnect_account  → revoke tokens and remove an account by id.",
  "",
  "Two-stage setup. Stage 1 is one-time, per-deployment app credentials (client_id / client_secret).",
  "Stage 2 is per-user OAuth (the connect URL flow). The agent cannot do stage 1 for the user — it",
  "requires a human in the Google Cloud console — but it MUST walk the user through it when missing.",
  "",
  "Stage 1 — app credentials (only needed once, when SYSTEM_STARTUP_WARNINGS reports them missing).",
  "The user only ever needs to hand you two strings: client_id and client_secret. You persist them.",
  "Walk them through the GCP side, then ask for the two values and store them yourself — never tell",
  "them to export shell vars, edit config.json, or restart anything.",
  "  a. Tell the user to open https://console.cloud.google.com/ and either pick a project or create",
  "     one (any name works).",
  "  b. APIs & Services → OAuth consent screen → configure as 'External', add their own email as a",
  "     test user, and enable the Calendar, Gmail, and Drive APIs under 'Enabled APIs & services'.",
  "  c. APIs & Services → Credentials → Create credentials → OAuth client ID → application type",
  "     'Web application'. Under 'Authorized redirect URIs' add the gateway's callback URL —",
  "     `<gateway-base-url>/oauth/google/callback`. Read the gateway base URL straight off the",
  "     `Runtime environment` section of the system prompt (use the **Dashboard URL** value",
  "     verbatim — never guess the port). The SYSTEM_STARTUP_WARNINGS credentials message also",
  "     prints the exact redirect URI for this gateway.",
  "  d. Hit 'Download JSON' on the new client. Tell the user to open the downloaded",
  "     `client_secret_xxx.apps.googleusercontent.com.json` and copy `web.client_id` and",
  "     `web.client_secret` to you. The file itself is NOT read by the gateway; only those two",
  "     strings matter, so dropping the JSON into ~/.squad does nothing on its own.",
  "  e. Once they paste the two values, persist each with set_env — it writes to the gateway's",
  "     secrets file (survives restarts), injects into process.env immediately, and the plugin",
  "     re-reads process.env on every OAuth call, so the change takes effect right away — no",
  "     gateway restart needed:",
  "       set_env({name: 'GOOGLE_CLIENT_ID',     value: '<the client_id>'})",
  "       set_env({name: 'GOOGLE_CLIENT_SECRET', value: '<the client_secret>'})",
  "     If list_env_names already shows one of these, confirm with the user before overwriting.",
  "  f. Move straight to stage 2 — no restart required. The missing-creds startup warning will",
  "     clear on the next request.",
  "",
  "Stage 2 — connect a user account (every Google account, including the first one):",
  "  1. Call google_list_accounts to see what is already connected.",
  "  2. If nothing is connected (or the needed feature isn't enabled), call google_connect_url and",
  "     hand the URL to the user — do not try to follow the OAuth flow yourself. They open it in a",
  "     browser, approve consent, and Google redirects back to the gateway, which writes encrypted",
  "     tokens to sqlite.",
  "  3. Once an account is connected, the calendar / gmail / drive tool groups become usable.",
  "",
  "Common stage-1 failure: 'Access blocked: invalid_request — Missing required parameter: client_id'",
  "on the Google consent screen means the gateway started with an empty client_id and forwarded it.",
  "Re-run stage 1 — the env vars probably weren't exported in the same shell, or the gateway wasn't",
  "restarted after editing config.json.",
  "",
  "Account ids look like `ga_xxxxxxxxxxxx`. Disconnect both revokes the OAuth tokens upstream and",
  "drops the row locally — irreversible without re-consenting.",
].join("\n");
