export const CRON_GUIDANCE = [
  "Cron jobs let you schedule recurring or one-off work — agent prompts, scripts, or script-then-prompt chains.",
  "",
  "When to create a cron job:",
  '  - The user asks for "every / nightly / weekly / daily" automation.',
  '  - A one-shot future action ("remind me at 5pm", "open a cleanup PR in 2 weeks").',
  '  - A polling check ("check the deploy every 5 minutes until it lands").',
  "",
  "Schedule kinds:",
  '  - cron     → 5-field crontab, e.g. { kind: "cron", expr: "0 9 * * 1-5" } for 9am weekdays.',
  '  - interval → { kind: "interval", everyMs: 1800000 } for every 30 minutes.',
  '  - once     → { kind: "once", at: "2026-05-10T17:00:00Z" }; the job auto-disables after firing.',
  "",
  "Payload kinds (pick one):",
  '  - prompt           → run an agent turn. Pass { messages: [{ role: "user", text }] }.',
  "                       Add system messages for a custom system prompt; add skills[] to load skill instructions.",
  '  - script           → spawn a shell command (no LLM). Cheap; use for data collection,',
  "                       health checks, or anything that just needs to run code.",
  '  - scriptThenPrompt → run a script, then feed its stdout into an agent turn.',
  "                       Use {{output}} in any prompt message to splice the script's stdout in.",
  "                       If no message contains {{output}}, the stdout is appended as a final user message.",
  "                       Conditional: exit 0 → run the agent. Non-zero exit → status=error, no agent.",
  "                       Exit 0 with empty stdout → status=skipped, no agent (\"nothing to do\" path).",
  "",
  "Session targeting:",
  '  - new       → fresh session per fire (default; safe choice).',
  '  - isolated  → fresh session that does not show up in dashboards.',
  '  - session   → append to a specific existing session (use this for "agent picks up where it left off").',
  "",
  "Per-job model override: set execution.model (e.g. claude-haiku-4-5 for a cheap tick).",
  "Tool restriction: set execution.toolsAllow to constrain what tools the agent can call this run.",
  "Wake gate (script payload): print '[SILENT]' on the first line to skip delivery (run still logged).",
  "",
  "Delivery (where the output goes):",
  "  - silent     → run logged, nothing sent anywhere.",
  "  - dashboard  → open the resulting session in the chat UI (default).",
  "  - discord    → post into a channel. Set channelId (and optional guildId).",
  "  - <plugin>   → any other kind routes to a plugin-registered handler",
  "                 (e.g. 'slack'). Pass that plugin's required fields under `extras`.",
  '  Examples: { kind: "discord", channelId: "1234..." }',
  '            { kind: "slack", extras: { channel: "#alerts" } }',
  "",
  "Scripts: spawned via `child_process.spawn(command, args, { cwd })`. cwd defaults to the gateway",
  "workspace dir; env is the gateway's process env. stdout+stderr are captured (capped 64KB), and",
  "the run is killed at min(execution.timeoutSec, 300s).",
  "",
  "After creating, you can call run_cron_job to fire it once immediately. Use list_cron_jobs",
  "to find an id, get_cron_runs to inspect history.",
].join("\n");
