export const CRON_GUIDANCE = [
  "Cron jobs let you schedule recurring or one-off work — prompts, scripts, or full agent turns.",
  "",
  "When to create a cron job:",
  '  - The user asks for "every / nightly / weekly / daily" automation.',
  '  - A one-shot future action ("remind me at 5pm", "open a cleanup PR in 2 weeks").',
  '  - A polling check ("check the deploy every 5 minutes until it lands").',
  "",
  "Schedule kinds:",
  '  - cron     → 5-field crontab, e.g. { kind: "cron", expr: "0 9 * * 1-5" } for 9am weekdays.',
  '  - interval → { kind: "interval", everyMs: 1800000 } for every 30 minutes.',
  '  - once     → { kind: "once", at: "2026-05-10T17:00:00Z" }; the job auto-disables after firing.',
  "",
  "Payload kinds (pick one):",
  '  - prompt    → run an agent turn with this text. Best default for most jobs.',
  '  - agentTurn → explicit user/system messages when you need a custom system prompt.',
  '  - script    → spawn a shell command (no LLM). Cheap; use for data collection,',
  "                health checks, or anything that just needs to run code.",
  "",
  "Session targeting:",
  '  - new       → fresh session per fire (default; safe choice).',
  '  - isolated  → fresh session that does not show up in dashboards.',
  '  - session   → append to a specific existing session.',
  "",
  "Per-job model override: set execution.model (e.g. claude-haiku-4-5 for a cheap tick).",
  "Skills (prompt payload): inject skill names so the run loads those skill instructions.",
  "Wake gate: a script payload that prints '[SILENT]' on the first line skips delivery.",
  "",
  "After creating, you can call run_cron_job to fire it once immediately. Use list_cron_jobs",
  "to find an id, get_cron_runs to inspect history.",
].join("\n");
