#!/usr/bin/env node
// Interactive Squad setup wizard.
//
// Walks the user through the minimum config + secrets needed to launch the
// gateway, then writes them to ~/.squad/squads/<name>/{config.json,.env}.
// The bind mount target inside each container is /app/docker/, so the
// generated config keeps using that as its data_dir.
//
// Pass --squad <name> to set up a specific squad. Defaults to 'default'.
//
// Re-runnable: detects existing files and offers to keep, overwrite, or merge
// individual values. No external deps so it works before `pnpm install`.

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin, stdout, argv, env, exit } from "node:process";
import { randomBytes } from "node:crypto";
import { execSync } from "node:child_process";
import { homedir } from "node:os";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");

// Pick the squad to set up: --squad <name>, else 'default'.
function getFlagValue(name) {
  const i = argv.indexOf(name);
  if (i === -1 || i + 1 >= argv.length) return undefined;
  return argv[i + 1];
}
const SQUAD_NAME = getFlagValue("--squad") || "default";
if (!/^[a-z0-9][a-z0-9_-]{0,30}$/.test(SQUAD_NAME)) {
  console.error(`invalid squad name '${SQUAD_NAME}': lowercase alnum/_/-, ≤31 chars.`);
  exit(2);
}

const HOME = env.HOME || env.USERPROFILE || homedir();
const SQUAD_HOME = join(HOME, ".squad");
const REGISTRY_PATH = join(SQUAD_HOME, "squads.json");
const COMPOSE_PATH = join(SQUAD_HOME, "docker-compose.yml");
const CURRENT_FILE = join(SQUAD_HOME, "current");
const SQUAD_DIR = join(SQUAD_HOME, "squads", SQUAD_NAME);
const CONFIG_PATH = join(SQUAD_DIR, "config.json");
const ENV_PATH = join(SQUAD_DIR, ".env");
const DATA_DIR = join(SQUAD_DIR, "data");
const SEARXNG_DIR = join(SQUAD_HOME, "shared", "searxng");
const SEARXNG_SETTINGS = join(SEARXNG_DIR, "settings.yml");

function seedSearxngSettings() {
  if (existsSync(SEARXNG_SETTINGS)) return;
  mkdirSync(SEARXNG_DIR, { recursive: true });
  const secret = randomBytes(32).toString("hex");
  const yaml = `# Auto-generated by scripts/setup.mjs. Re-run with --force to regenerate.
#
# SearXNG powers the built-in web_search tool. The JSON format is enabled so
# the tool can parse results; without this, SearXNG returns 403 and the tool
# falls back to DuckDuckGo HTML scraping.
use_default_settings: true

general:
  instance_name: "squad-searxng"
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${secret}"
  base_url: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"

ui:
  static_use_hash: true
  default_locale: "en"

redis:
  url: false
`;
  writeFileSync(SEARXNG_SETTINGS, yaml);
}

const FORCE = argv.includes("--force") || argv.includes("-f");
const NON_INTERACTIVE = argv.includes("--yes") || argv.includes("-y");

const rl = createInterface({ input: stdin, output: stdout });

function bold(s) {
  return `\x1b[1m${s}\x1b[0m`;
}
function dim(s) {
  return `\x1b[2m${s}\x1b[0m`;
}
function green(s) {
  return `\x1b[32m${s}\x1b[0m`;
}
function yellow(s) {
  return `\x1b[33m${s}\x1b[0m`;
}
function red(s) {
  return `\x1b[31m${s}\x1b[0m`;
}
function cyan(s) {
  return `\x1b[36m${s}\x1b[0m`;
}

/**
 * Step header. Printed before each section so the user can see progress and
 * whether the section is required or optional.
 */
function stepHeader(n, total, title, required) {
  const tag = required ? green("required") : dim("optional");
  console.log(
    `\n${cyan(`── Step ${n}/${total}`)} ${bold(title)}  ${tag}`,
  );
}

/**
 * Single-select picker with ↑/↓ navigation. Returns the chosen option label.
 * Falls back to `options[defaultIdx]` when non-TTY or NON_INTERACTIVE.
 *
 * Zero-deps on purpose — this script runs before `pnpm install`, so we can't
 * rely on enquirer/inquirer/prompts.
 */
async function pickOne(title, options, defaultIdx = 0) {
  if (NON_INTERACTIVE || !stdin.isTTY) {
    return options[Math.max(0, Math.min(defaultIdx, options.length - 1))];
  }
  rl.pause();
  stdin.setRawMode(true);
  stdin.resume();

  let cursor = Math.max(0, Math.min(defaultIdx, options.length - 1));
  const totalLines = options.length + 2; // title + hint + rows

  const paint = (first) => {
    if (!first) process.stdout.write(`\x1b[${totalLines}A`);
    process.stdout.write(`${title}\x1b[K\n`);
    process.stdout.write(dim("  ↑/↓ to move, enter to select") + "\x1b[K\n");
    for (let i = 0; i < options.length; i++) {
      const marker = i === cursor ? cyan("❯") : " ";
      const label = i === cursor ? bold(options[i]) : options[i];
      process.stdout.write(`${marker} ${label}\x1b[K\n`);
    }
  };
  paint(true);

  return new Promise((resolveP) => {
    const onData = (buf) => {
      const s = buf.toString();
      if (s === "\r" || s === "\n") {
        stdin.removeListener("data", onData);
        stdin.setRawMode(false);
        stdin.pause();
        rl.resume();
        resolveP(options[cursor]);
      } else if (s === "\x03") {
        stdin.setRawMode(false);
        process.exit(130);
      } else if (s === "\x1b[A" || s === "k") {
        cursor = (cursor - 1 + options.length) % options.length;
        paint(false);
      } else if (s === "\x1b[B" || s === "j") {
        cursor = (cursor + 1) % options.length;
        paint(false);
      }
    };
    stdin.on("data", onData);
  });
}

/**
 * Multi-select picker. Space toggles the current row, `a` toggles all, enter
 * confirms. Returns a Set of chosen indices (0-based). Falls back to the
 * preselected set in non-TTY mode.
 */
async function pickMany(title, options, preselected = new Set()) {
  if (NON_INTERACTIVE || !stdin.isTTY) {
    return new Set(preselected);
  }
  rl.pause();
  stdin.setRawMode(true);
  stdin.resume();

  let cursor = 0;
  const selected = new Set(preselected);
  const totalLines = options.length + 2;

  const paint = (first) => {
    if (!first) process.stdout.write(`\x1b[${totalLines}A`);
    process.stdout.write(`${title}\x1b[K\n`);
    process.stdout.write(
      dim("  ↑/↓ to move, space to toggle, a to toggle all, enter to confirm") +
        "\x1b[K\n",
    );
    for (let i = 0; i < options.length; i++) {
      const cur = i === cursor ? cyan("❯") : " ";
      const mark = selected.has(i) ? green("◉") : dim("◯");
      const label = i === cursor ? bold(options[i]) : options[i];
      process.stdout.write(`${cur} ${mark} ${label}\x1b[K\n`);
    }
  };
  paint(true);

  return new Promise((resolveP) => {
    const onData = (buf) => {
      const s = buf.toString();
      if (s === "\r" || s === "\n") {
        stdin.removeListener("data", onData);
        stdin.setRawMode(false);
        stdin.pause();
        rl.resume();
        resolveP(selected);
      } else if (s === "\x03") {
        stdin.setRawMode(false);
        process.exit(130);
      } else if (s === "\x1b[A" || s === "k") {
        cursor = (cursor - 1 + options.length) % options.length;
        paint(false);
      } else if (s === "\x1b[B" || s === "j") {
        cursor = (cursor + 1) % options.length;
        paint(false);
      } else if (s === " ") {
        if (selected.has(cursor)) selected.delete(cursor);
        else selected.add(cursor);
        paint(false);
      } else if (s === "a" || s === "A") {
        if (selected.size === options.length) selected.clear();
        else for (let i = 0; i < options.length; i++) selected.add(i);
        paint(false);
      }
    };
    stdin.on("data", onData);
  });
}

/**
 * Ask whether to skip an optional step. Returns `true` for skip. Honors a
 * `previouslyConfigured` hint so re-runs default to "keep configuring it".
 */
async function skipPrompt(previouslyConfigured) {
  if (NON_INTERACTIVE) return !previouslyConfigured;
  const defSkip = !previouslyConfigured;
  const suffix = defSkip ? "[Y/n]" : "[y/N]";
  while (true) {
    const raw = (await rl.question(`  Skip this step? ${suffix} `)).trim().toLowerCase();
    if (!raw) return defSkip;
    if (["y", "yes", "s", "skip"].includes(raw)) return true;
    if (["n", "no"].includes(raw)) return false;
    console.log(red("  please answer yes or no"));
  }
}

async function ask(prompt, { default: def, secret = false } = {}) {
  if (NON_INTERACTIVE) return def ?? "";
  const suffix = def ? dim(` [${secret ? mask(def) : def}]`) : "";
  const answer = (await rl.question(`${prompt}${suffix} `)).trim();
  return answer || def || "";
}

async function askChoice(prompt, choices, def) {
  if (NON_INTERACTIVE) return def;
  const labels = choices
    .map((c, i) => `${i + 1}) ${c}${c === def ? dim(" (default)") : ""}`)
    .join("  ");
  while (true) {
    const raw = (await rl.question(`${prompt}\n  ${labels}\n> `)).trim();
    if (!raw) return def;
    const n = Number(raw);
    if (Number.isInteger(n) && n >= 1 && n <= choices.length) return choices[n - 1];
    if (choices.includes(raw)) return raw;
    console.log(red("  pick a number from the list above"));
  }
}

async function askYesNo(prompt, def = false) {
  if (NON_INTERACTIVE) return def;
  const suffix = def ? "[Y/n]" : "[y/N]";
  while (true) {
    const raw = (await rl.question(`${prompt} ${suffix} `)).trim().toLowerCase();
    if (!raw) return def;
    if (["y", "yes"].includes(raw)) return true;
    if (["n", "no"].includes(raw)) return false;
    console.log(red("  please answer yes or no"));
  }
}

function mask(secret) {
  if (!secret) return "";
  if (secret.length <= 8) return "***";
  return `${secret.slice(0, 4)}…${secret.slice(-4)}`;
}

function generateToken(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

/**
 * Read a git config value from the host (best-effort, used to pre-fill the
 * committer name/email prompts). Returns "" if git is absent or unset.
 */
function detectGitHost(key) {
  try {
    return execSync(`git config --global --get ${key}`, {
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    }).trim();
  } catch {
    return "";
  }
}

function ghInstalled() {
  try {
    execSync("gh --version", { stdio: ["ignore", "ignore", "ignore"] });
    return true;
  } catch {
    return false;
  }
}

/**
 * Squad keeps its own gh config sandbox under docker/data/gh/ so signing in
 * for the squad container doesn't overwrite the user's personal `gh auth` on
 * the host.
 */
const SQUAD_GH_DIR = join(DATA_DIR, "gh");

function ghEnv(configDir) {
  // Strip GITHUB_TOKEN / GH_TOKEN from the inherited env when calling gh —
  // otherwise gh sees the host's token and refuses to start the login flow.
  const e = { ...env };
  delete e.GITHUB_TOKEN;
  delete e.GH_TOKEN;
  if (configDir) e.GH_CONFIG_DIR = configDir;
  return e;
}

function detectGhToken(configDir) {
  try {
    return execSync("gh auth token", {
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
      env: ghEnv(configDir),
    }).trim();
  } catch {
    return "";
  }
}

function detectGhUser(configDir) {
  try {
    return execSync("gh api user --jq .login", {
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
      env: ghEnv(configDir),
    }).trim();
  } catch {
    return "";
  }
}

/**
 * Drive `gh auth login` against the squad-only sandbox dir. The host's
 * personal gh auth is left untouched. Returns { token, user }.
 */
function runGhAuthLoginSandboxed() {
  mkdirSync(SQUAD_GH_DIR, { recursive: true });
  try {
    execSync(
      "gh auth login --hostname github.com --git-protocol https --web",
      { stdio: "inherit", env: ghEnv(SQUAD_GH_DIR) },
    );
  } catch {
    return { token: "", user: "" };
  }
  return {
    token: detectGhToken(SQUAD_GH_DIR),
    user: detectGhUser(SQUAD_GH_DIR),
  };
}

// Minimal .env parser — KEY=VALUE per line, ignores comments and blanks.
function parseEnv(text) {
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  return parseEnv(readFileSync(path, "utf8"));
}

/**
 * Read or initialize ~/.squad/squads.json. Same shape as packages/client-cli's
 * Registry — duplicated here so setup.mjs has no dependencies (it runs before
 * `pnpm install`).
 */
function loadRegistry() {
  if (!existsSync(REGISTRY_PATH)) {
    return { build_context: REPO_ROOT, squads: [], shared: { searxng_port: 8888 } };
  }
  try {
    const parsed = JSON.parse(readFileSync(REGISTRY_PATH, "utf8"));
    return {
      build_context: parsed.build_context || REPO_ROOT,
      squads: Array.isArray(parsed.squads) ? parsed.squads : [],
      shared: { searxng_port: 8888, ...(parsed.shared ?? {}) },
    };
  } catch {
    return { build_context: REPO_ROOT, squads: [], shared: { searxng_port: 8888 } };
  }
}

function saveRegistry(reg) {
  mkdirSync(SQUAD_HOME, { recursive: true });
  writeFileSync(REGISTRY_PATH, JSON.stringify(reg, null, 2) + "\n");
}

function findFreeHostPort(reg, start = 8080) {
  const taken = new Set(reg.squads.map((s) => s.port));
  taken.add(reg.shared.searxng_port);
  let p = start;
  while (taken.has(p)) p++;
  return p;
}

/**
 * Insert/update this squad's entry in the registry, then regenerate
 * ~/.squad/docker-compose.yml. The compose generator lives in the built
 * client-cli; if dist isn't present, print a hint and continue (the user can
 * run `squad mgr regen` after building).
 */
function syncRegistryAndCompose(hostPort) {
  const reg = loadRegistry();
  const existing = reg.squads.find((s) => s.name === SQUAD_NAME);
  if (existing) {
    if (hostPort) existing.port = hostPort;
  } else {
    const port = hostPort ?? findFreeHostPort(reg);
    reg.squads.push({ name: SQUAD_NAME, port });
  }
  reg.build_context = REPO_ROOT;
  saveRegistry(reg);

  // Pin the just-configured squad as current so `squad chat` etc. target it
  // without --squad. Idempotent.
  mkdirSync(SQUAD_HOME, { recursive: true });
  writeFileSync(CURRENT_FILE, SQUAD_NAME + "\n");

  // Trigger compose regen via the built CLI. Falls back to a hint when dist
  // isn't built yet (first-time install).
  const cliBin = join(REPO_ROOT, "packages", "client-cli", "dist", "cli.js");
  if (existsSync(cliBin)) {
    try {
      execSync(`node ${JSON.stringify(cliBin)} mgr regen`, { stdio: "inherit" });
    } catch {
      console.log(yellow("  (compose regen failed — run 'squad mgr regen' once squad is built)"));
    }
  } else {
    console.log(
      dim(
        `  (skipping compose regen — packages/client-cli/dist not built yet. Run 'pnpm build && squad mgr regen'.)`,
      ),
    );
  }
}

/**
 * Known LLM providers the wizard can configure. Each maps to the env var that
 * holds the API key and a sensible default model to propose as the primary.
 * `keyUrl` is shown to the user so they know where to grab a key.
 *
 * The LLM package (packages/llm/src/client.ts) supports more providers than
 * these — listing every niche one here would be overwhelming. Users can still
 * add any provider by hand-editing docker/config.json after setup.
 */
const PROVIDERS = {
  anthropic: {
    label: "Anthropic (Claude)",
    envVar: "ANTHROPIC_API_KEY",
    defaultModel: "anthropic/claude-sonnet-4-5",
    keyUrl: "https://console.anthropic.com",
  },
  openai: {
    label: "OpenAI (GPT)",
    envVar: "OPENAI_API_KEY",
    defaultModel: "openai/gpt-4o",
    keyUrl: "https://platform.openai.com/api-keys",
  },
  openrouter: {
    label: "OpenRouter (~24 providers via one key)",
    envVar: "OPENROUTER_API_KEY",
    defaultModel: "openrouter/anthropic/claude-sonnet-4-5",
    keyUrl: "https://openrouter.ai/keys",
  },
  google: {
    label: "Google (Gemini)",
    envVar: "GOOGLE_API_KEY",
    defaultModel: "google/gemini-2.5-flash",
    keyUrl: "https://aistudio.google.com/apikey",
  },
  groq: {
    label: "Groq (fast inference)",
    envVar: "GROQ_API_KEY",
    defaultModel: "groq/llama-3.3-70b-versatile",
    keyUrl: "https://console.groq.com/keys",
  },
  deepseek: {
    label: "DeepSeek",
    envVar: "DEEPSEEK_API_KEY",
    defaultModel: "deepseek/deepseek-chat",
    keyUrl: "https://platform.deepseek.com/api_keys",
  },
  xai: {
    label: "xAI (Grok)",
    envVar: "XAI_API_KEY",
    defaultModel: "xai/grok-4",
    keyUrl: "https://console.x.ai",
  },
  together: {
    label: "Together.ai (open-weight models)",
    envVar: "TOGETHER_API_KEY",
    defaultModel: "together/meta-llama/Llama-3.3-70B-Instruct",
    keyUrl: "https://api.together.ai/settings/api-keys",
  },
  mistral: {
    label: "Mistral",
    envVar: "MISTRAL_API_KEY",
    defaultModel: "mistral/mistral-large-latest",
    keyUrl: "https://console.mistral.ai/api-keys/",
  },
  perplexity: {
    label: "Perplexity",
    envVar: "PPLX_API_KEY",
    defaultModel: "perplexity/sonar-pro",
    keyUrl: "https://www.perplexity.ai/settings/api",
  },
  fireworks: {
    label: "Fireworks",
    envVar: "FIREWORKS_API_KEY",
    defaultModel: "fireworks/accounts/fireworks/models/llama-v3p3-70b-instruct",
    keyUrl: "https://fireworks.ai/account/api-keys",
  },
  cerebras: {
    label: "Cerebras (very fast inference)",
    envVar: "CEREBRAS_API_KEY",
    defaultModel: "cerebras/llama-3.3-70b",
    keyUrl: "https://cloud.cerebras.ai",
  },
  cohere: {
    label: "Cohere",
    envVar: "COHERE_API_KEY",
    defaultModel: "cohere/command-r-plus",
    keyUrl: "https://dashboard.cohere.com/api-keys",
  },
  sambanova: {
    label: "SambaNova",
    envVar: "SAMBANOVA_API_KEY",
    defaultModel: "sambanova/Meta-Llama-3.3-70B-Instruct",
    keyUrl: "https://cloud.sambanova.ai/apis",
  },
  novita: {
    label: "Novita",
    envVar: "NOVITA_API_KEY",
    defaultModel: "novita/meta-llama/llama-3.3-70b-instruct",
    keyUrl: "https://novita.ai/settings/key-management",
  },
  hyperbolic: {
    label: "Hyperbolic",
    envVar: "HYPERBOLIC_API_KEY",
    defaultModel: "hyperbolic/meta-llama/Llama-3.3-70B-Instruct",
    keyUrl: "https://app.hyperbolic.xyz/settings",
  },
  lambda: {
    label: "Lambda Labs",
    envVar: "LAMBDA_API_KEY",
    defaultModel: "lambda/llama3.3-70b-instruct-fp8",
    keyUrl: "https://cloud.lambda.ai/api-keys",
  },
  "z-ai": {
    label: "Z.AI (GLM)",
    envVar: "ZAI_API_KEY",
    defaultModel: "z-ai/glm-4.6",
    keyUrl: "https://docs.z.ai/guides/manage-api-key",
  },
  minimax: {
    label: "MiniMax",
    envVar: "MINIMAX_API_KEY",
    defaultModel: "minimax/minimax-m2.7",
    keyUrl: "https://www.minimax.io/platform/user-center/basic-information/interface-key",
  },
  kimi: {
    label: "Kimi (Moonshot)",
    envVar: "KIMI_API_KEY",
    defaultModel: "kimi/kimi-k2.5",
    keyUrl: "https://platform.moonshot.cn/console/api-keys",
  },
  "opencode-zen": {
    label: "OpenCode Zen (frontier subscription)",
    envVar: "OPENCODE_API_KEY",
    defaultModel: "opencode-zen/claude-sonnet-4",
    keyUrl: "https://opencode.ai",
  },
  "opencode-go": {
    label: "OpenCode Go (open-weight subscription)",
    envVar: "OPENCODE_API_KEY",
    defaultModel: "opencode-go/kimi-k2.5",
    keyUrl: "https://opencode.ai",
  },
};

// Deduped — multiple providers can share an env var (e.g. opencode-zen and
// opencode-go both use OPENCODE_API_KEY).
const PROVIDER_ENV_VARS = [
  ...new Set(Object.values(PROVIDERS).map((p) => p.envVar)),
];

/**
 * Render a single KEY=VALUE line. Quotes the value when it contains anything
 * that would confuse `bash` when the file is sourced (`set -a; . file`) —
 * spaces, quotes, $, etc. Empty values render as `KEY=` (no quotes).
 */
function envLine(key, value) {
  const v = value ?? "";
  if (v === "") return `${key}=`;
  if (/[\s"'$`\\!&|;<>(){}*?#~]/.test(v)) {
    // Single-quote and escape any embedded single quotes via the standard
    // POSIX trick: end-quote, escape, re-open: '\''.
    return `${key}='${v.replace(/'/g, "'\\''")}'`;
  }
  return `${key}=${v}`;
}

function renderEnv(values) {
  const lines = [
    "# Generated by scripts/setup.mjs — re-run `squad onboard` to change.",
    "# This file holds secrets. It is gitignored. Do NOT commit it.",
    "",
    "# --- Server ---",
    "# Port the gateway listens on. docker-compose maps host:container 1:1, and",
    "# the squad CLI uses this to build its default SQUAD_URL.",
    envLine("SQUAD_PORT", values.SQUAD_PORT ?? "8080"),
    "",
    "# --- Local web search (SearXNG) ---",
    "# Host port for the docker-compose searxng sidecar. The gateway inside the",
    "# container talks to the service hostname (http://searxng:8080) regardless",
    "# of this — SEARXNG_PORT only affects host-side access and `pnpm start:local`.",
    envLine("SEARXNG_PORT", values.SEARXNG_PORT ?? "8888"),
    "",
    "# --- Dashboard auth ---",
    "# Bearer token for the dashboard + any first-party clients. Treat as a password.",
    envLine("SQUAD_DASHBOARD_TOKEN", values.SQUAD_DASHBOARD_TOKEN),
    "",
    "# --- LLM providers (at least one required) ---",
  ];
  for (const key of PROVIDER_ENV_VARS) {
    const v = values[key];
    lines.push(v ? envLine(key, v) : `# ${key}=`);
  }
  lines.push(
    "",
    "# --- Git identity (used by container for commits + gh cli) ---",
    envLine("GIT_USER_NAME", values.GIT_USER_NAME),
    envLine("GIT_USER_EMAIL", values.GIT_USER_EMAIL),
    values.GITHUB_TOKEN ? envLine("GITHUB_TOKEN", values.GITHUB_TOKEN) : "# GITHUB_TOKEN=",
    "",
    "# --- Optional Discord channel ---",
  );
  for (const k of ["DISCORD_BOT_TOKEN", "SQUAD_DISCORD_TOKEN"]) {
    const v = values[k];
    lines.push(v ? envLine(k, v) : `# ${k}=`);
  }
  // Carry over any unknown keys the user added by hand.
  const known = new Set([
    "SQUAD_PORT",
    "SEARXNG_PORT",
    "SQUAD_DASHBOARD_TOKEN",
    "GIT_USER_NAME",
    "GIT_USER_EMAIL",
    "GITHUB_TOKEN",
    "DISCORD_BOT_TOKEN",
    "SQUAD_DISCORD_TOKEN",
    ...PROVIDER_ENV_VARS,
  ]);
  const extras = Object.entries(values).filter(([k, v]) => !known.has(k) && v);
  if (extras.length) {
    lines.push("", "# --- Other ---");
    for (const [k, v] of extras) lines.push(envLine(k, v));
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * Merge wizard-collected values into the existing config (or a fresh shell on
 * first run). Anything the wizard doesn't manage — subagents, policy,
 * plugins, custom auth tokens, custom channels, hand-edited extensions — is
 * preserved as-is.
 */
function renderConfig(existing, opts) {
  const cfg = existing
    ? { ...existing }
    : {
        $comment:
          "Generated by scripts/setup.mjs — re-run `squad onboard` to change. Safe to edit by hand; the wizard preserves unknown keys on re-run.",
      };

  // server: container always listens on 8080 internally; the host-side port
  // is controlled by the docker-compose port mapping (managed by mgr regen).
  // data_dir is the in-container path that maps to ~/.squad/squads/<name>/data
  // via the bind mount.
  cfg.server = {
    host: "0.0.0.0",
    ...(cfg.server ?? {}),
    data_dir: "/app/docker/data",
    port: 8080,
  };

  // auth.tokens: preserve user-added tokens; upsert dashboard + discord-connector.
  const existingTokens = (cfg.auth?.tokens ?? []).filter(
    (t) => t.label !== "dashboard" && t.label !== "discord-connector",
  );
  const tokens = [
    { label: "dashboard", key_env: "SQUAD_DASHBOARD_TOKEN", scopes: ["*"] },
    ...existingTokens,
  ];
  if (opts.discord) {
    tokens.push({
      label: "discord-connector",
      key_env: "SQUAD_DISCORD_TOKEN",
      scopes: ["channel:discord", "chat.*", "session.*"],
    });
  }
  cfg.auth = { ...(cfg.auth ?? {}), tokens };

  cfg.chat = { ...(cfg.chat ?? {}), delivery: opts.delivery };

  // Discord is a plugin, not a first-class gateway concept. Strip any legacy
  // `channels.discord` entry from old configs and upsert the plugin record.
  if (cfg.channels && typeof cfg.channels === "object") {
    delete cfg.channels.discord;
    if (Object.keys(cfg.channels).length === 0) delete cfg.channels;
  }

  // Subagents / policy: keep user's customizations if present; otherwise seed
  // sensible defaults. Wizard never collects these.
  cfg.subagents = cfg.subagents ?? {
    max_concurrent_global: 8,
    max_concurrent_per_parent: 4,
    max_tree_depth: 3,
  };
  cfg.policy = cfg.policy ?? {
    approvals: {
      default: "tag-match",
      require_for_tags: ["write", "exec", "network"],
      timeout_seconds: 120,
    },
  };

  // plugins: preserve user-added entries; upsert the Discord plugin iff the
  // user provided a bot token (remove it otherwise so stale tokens don't
  // linger after `pnpm setup` with Discord deselected).
  // Relative to the gateway's cwd (packages/gateway in both docker and local
  // modes, since `pnpm --filter @squad/gateway start` runs there).
  const DISCORD_PLUGIN_PATH = "../channel-discord/dist/plugin.js";
  const existingPlugins = Array.isArray(cfg.plugins) ? cfg.plugins : [];
  // Preserve the user's existing Discord plugin config on re-run (they may
  // have hand-edited the allow-list or DM policy). Only overwrite when it's
  // not present. Non-Discord plugin entries pass through untouched.
  const existingDiscord = existingPlugins.find(
    (p) => typeof p === "object" && p?.path === DISCORD_PLUGIN_PATH,
  );
  const withoutDiscord = existingPlugins.filter((p) => {
    if (typeof p === "string") return p !== DISCORD_PLUGIN_PATH;
    return p?.path !== DISCORD_PLUGIN_PATH;
  });
  if (opts.discord) {
    withoutDiscord.push({
      path: DISCORD_PLUGIN_PATH,
      config: {
        bot_token_env: "DISCORD_BOT_TOKEN",
        gateway_token_env: "SQUAD_DISCORD_TOKEN",
        gateway_url: "ws://127.0.0.1:8080/ws",
        // Safe default: only known users can DM the bot. Admins add snowflake
        // IDs here (or switch `dm_policy` to "open" / "blocked") after setup.
        dm_policy: "allow_list",
        dm_allow_list: [],
        ...(existingDiscord?.config ?? {}),
      },
    });
  }
  cfg.plugins = withoutDiscord;

  // llm.providers — replace fully (this is the wizard's domain). Unticked
  // providers are intentionally dropped from the active list.
  const providers = {};
  for (const name of opts.providers ?? []) {
    const spec = PROVIDERS[name];
    if (spec) providers[name] = { api_key_env: spec.envVar };
  }

  cfg.llm = {
    ...(cfg.llm ?? {}),
    primary: { model: opts.primaryModel },
    fallbacks: opts.fallbacks.map((m) => ({ model: m })),
    providers,
  };

  return JSON.stringify(cfg, null, 2) + "\n";
}

async function main() {
  console.log(bold(`\nSquad setup wizard — squad '${SQUAD_NAME}'\n`));
  console.log(
    `Writes ${dim(`~/.squad/squads/${SQUAD_NAME}/{config.json,.env}`)} — the bind-mounted state read by the squad container.`,
  );
  console.log(
    dim(`Pass --squad <name> to set up a different squad. Run 'squad mgr ls' to see them all.\n`),
  );

  mkdirSync(SQUAD_HOME, { recursive: true });
  if (!existsSync(SQUAD_DIR)) {
    mkdirSync(SQUAD_DIR, { recursive: true });
    console.log(green(`✓ created ${SQUAD_DIR}`));
  }
  if (!existsSync(DATA_DIR)) {
    mkdirSync(DATA_DIR, { recursive: true });
    console.log(green(`✓ created ${DATA_DIR}/ (sqlite + uploads land here)`));
  }

  const existingEnv = loadEnvFile(ENV_PATH);
  const configExists = existsSync(CONFIG_PATH);

  if ((Object.keys(existingEnv).length || configExists) && !FORCE) {
    console.log(
      yellow(
        `Found existing setup at ${SQUAD_DIR}. Each step pre-fills the current value; press Enter to keep it, or pass --force to start clean.`,
      ),
    );
  }
  console.log(
    dim(
      `Optional steps can be skipped. You can re-run this wizard any time to fill them in later.`,
    ),
  );

  const TOTAL = 8;
  const summary = [];
  const providerKeys = {}; // env var name -> secret value, for configured providers
  const configuredProviders = []; // provider names (keys of PROVIDERS)

  // ── Step 1: LLM providers (required — at least one) ──────────────────
  stepHeader(1, TOTAL, "LLM providers", true);
  console.log(
    dim("  Pick one or more providers. You can add more later by re-running onboard."),
  );
  const providerList = Object.entries(PROVIDERS);
  const labels = providerList.map(([_n, spec]) =>
    existingEnv[spec.envVar] ? `${spec.label} ${green("✓ set")}` : spec.label,
  );
  const preselectedIdx = new Set(
    providerList
      .map(([_n, spec], i) => (existingEnv[spec.envVar] ? i : -1))
      .filter((i) => i >= 0),
  );
  // No pre-check on first run — the user picks explicitly with space.
  const pickedIdx = await pickMany("  Providers:", labels, preselectedIdx);
  if (pickedIdx.size === 0) {
    console.log(red("\n✗ at least one provider is required. Aborting."));
    exit(1);
  }
  // For each picked provider, reuse the existing key silently if there is
  // one — re-prompting would force the user to re-paste secrets to make any
  // unrelated edit. Only prompt for *newly added* providers.
  for (const n of [...pickedIdx].sort((a, b) => a - b)) {
    const [name, spec] = providerList[n];
    const existing = existingEnv[spec.envVar] || "";
    if (existing) {
      providerKeys[spec.envVar] = existing;
      configuredProviders.push(name);
      continue;
    }
    const key = await ask(
      `  ${bold(spec.label)} ${dim(spec.keyUrl)}`,
      { secret: true },
    );
    if (key) {
      providerKeys[spec.envVar] = key;
      configuredProviders.push(name);
    } else {
      console.log(dim(`  (skipped — no key provided for ${spec.label})`));
    }
  }
  if (configuredProviders.length === 0) {
    console.log(red("\n✗ no provider keys provided. Aborting."));
    exit(1);
  }

  // Note: any provider env var the user *unchecked* this run stays in .env
  // — onboard is non-destructive. To remove a key entirely, edit .env by hand.
  const droppedFromConfig = providerList
    .filter(([name]) => !configuredProviders.includes(name))
    .filter(([_n, spec]) => existingEnv[spec.envVar])
    .map(([name]) => name);
  if (droppedFromConfig.length) {
    console.log(
      dim(
        `  (kept in .env but removed from config.json llm.providers: ${droppedFromConfig.join(", ")})`,
      ),
    );
  }

  summary.push(`providers: ${configuredProviders.join(", ")}`);

  // ── Step 2: Primary model + fallbacks (required) ─────────────────────
  stepHeader(2, TOTAL, "Primary model + fallbacks", true);
  console.log(
    dim(
      "  Primary is the model the runner tries first. Fallbacks are used in order if the primary errors.",
    ),
  );

  let defaultPrimary = null;
  if (existingEnv.__previousPrimary) defaultPrimary = existingEnv.__previousPrimary;
  const defaultProvider =
    configuredProviders[0] ?? "anthropic";
  const suggestedPrimary = PROVIDERS[defaultProvider]?.defaultModel ?? "anthropic/claude-sonnet-4-5";

  const primaryProvider =
    configuredProviders.length === 1
      ? configuredProviders[0]
      : await pickOne(
          `  ${bold("Default provider")} ${dim("(used to suggest the primary model)")}`,
          configuredProviders,
          configuredProviders.indexOf(defaultProvider),
        );
  const primaryModel = await ask(`  ${bold("Primary model")}`, {
    default: defaultPrimary || PROVIDERS[primaryProvider].defaultModel,
  });

  // Offer fallbacks from any other configured providers.
  const fallbackSuggestions = configuredProviders
    .filter((p) => p !== primaryProvider)
    .map((p) => PROVIDERS[p].defaultModel)
    .join(", ");
  const fallbacksRaw = await ask(
    `  ${bold("Fallbacks")} ${dim("(comma-separated, blank for none)")}`,
    { default: fallbackSuggestions },
  );
  const fallbacks = fallbacksRaw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  summary.push(
    `primary ${primaryModel}${fallbacks.length ? ", " + fallbacks.length + " fallback(s)" : ""}`,
  );

  // ── Step 3: Server basics (required, good defaults) ─────────────────
  stepHeader(3, TOTAL, "Server port + dashboard token", true);
  console.log(dim("  Port the gateway exposes; bearer token for the web UI."));
  // Default to: explicit env > existing .env > existing registry entry for
  // this squad > the next free port across all registered squads. This
  // prevents two `--squad alpha` / `--squad beta` runs from both landing on
  // 8080 by default.
  const reg = loadRegistry();
  const existingSquadEntry = reg.squads.find((s) => s.name === SQUAD_NAME);
  const defaultPort =
    env.SQUAD_PORT ||
    existingEnv.SQUAD_PORT ||
    (existingSquadEntry ? String(existingSquadEntry.port) : String(findFreeHostPort(reg)));
  const port = await ask(`  ${bold("Port")}`, { default: defaultPort });
  const dashboardDefault =
    existingEnv.SQUAD_DASHBOARD_TOKEN && existingEnv.SQUAD_DASHBOARD_TOKEN !== "dev-dashboard-token"
      ? existingEnv.SQUAD_DASHBOARD_TOKEN
      : generateToken();
  const dashboardToken = await ask(`  ${bold("Dashboard token")}`, {
    default: dashboardDefault,
    secret: true,
  });
  summary.push(`server :${port}, dashboard token`);

  // ── Step 4: Chat delivery mode (required, default interrupt) ─────────
  stepHeader(4, TOTAL, "Chat delivery mode", true);
  console.log(
    dim(
      "  interrupt: inject new messages at the next LLM turn. queue: wait for the current run to finish.",
    ),
  );
  const delivery = await pickOne(
    `  ${bold("Delivery mode")}`,
    ["interrupt", "queue"],
    0,
  );
  summary.push(`delivery=${delivery}`);

  // ── Step 5: Git identity (optional) ─────────────────────────────────
  stepHeader(5, TOTAL, "Git committer identity", false);
  console.log(
    dim(
      "  Used when agents run `git commit` inside the container. Pre-filled from your host git config if present.",
    ),
  );
  const gitPrev = Boolean(existingEnv.GIT_USER_NAME || existingEnv.GIT_USER_EMAIL);
  let gitUserName = "";
  let gitUserEmail = "";
  if (await skipPrompt(gitPrev)) {
    gitUserName = existingEnv.GIT_USER_NAME ?? "";
    gitUserEmail = existingEnv.GIT_USER_EMAIL ?? "";
    summary.push(dim("git identity: skipped"));
  } else {
    const hostName = detectGitHost("user.name");
    const hostEmail = detectGitHost("user.email");
    gitUserName = await ask(`  ${bold("Name")}`, {
      default: existingEnv.GIT_USER_NAME || hostName || "",
    });
    gitUserEmail = await ask(`  ${bold("Email")}`, {
      default: existingEnv.GIT_USER_EMAIL || hostEmail || "",
    });
    summary.push(`git as ${gitUserName || "(unset)"} <${gitUserEmail || "(unset)"}>`);
  }

  // ── Step 6: GitHub token (optional) ─────────────────────────────────
  stepHeader(6, TOTAL, "GitHub token", false);
  console.log(
    dim(
      "  Enables `gh` CLI + HTTPS git auth inside the container. Squad keeps its own gh login under docker/data/gh/ — your host's personal `gh auth` stays untouched.",
    ),
  );
  let githubToken = "";
  const ghPrev = Boolean(existingEnv.GITHUB_TOKEN);
  const hasGh = ghInstalled();

  // Three possible sources of an existing token, listed top → bottom by
  // preference for "this is the squad account, not your personal one":
  //   1. Saved squad gh sandbox at docker/data/gh/   (squad-owned)
  //   2. Host's default gh auth                       (your personal account)
  //   3. A PAT you'll paste                           (manual)
  const squadGhToken = hasGh ? detectGhToken(SQUAD_GH_DIR) : "";
  const squadGhUser = squadGhToken ? detectGhUser(SQUAD_GH_DIR) : "";
  const hostGhToken = hasGh ? detectGhToken(undefined) : "";
  const hostGhUser = hostGhToken ? detectGhUser(undefined) : "";

  if (await skipPrompt(ghPrev || squadGhToken || hostGhToken)) {
    githubToken = existingEnv.GITHUB_TOKEN ?? "";
    summary.push(dim("GitHub token: skipped"));
  } else {
    const choices = [];
    if (squadGhToken) {
      const tag = squadGhUser ? `@${squadGhUser}` : mask(squadGhToken);
      choices.push({
        key: "squad",
        label: `Use squad's saved gh login (${tag})`,
      });
    }
    if (hasGh) {
      choices.push({
        key: "login",
        label: squadGhToken
          ? "Sign in again as a different account (replaces saved login)"
          : "Sign in to GitHub now via `gh auth login` (web/device flow)",
      });
    }
    if (hostGhToken && hostGhUser !== squadGhUser) {
      const tag = hostGhUser
        ? `@${hostGhUser} ${dim("— your personal host account")}`
        : mask(hostGhToken);
      choices.push({ key: "host", label: `Use host gh token (${tag})` });
    }
    choices.push({ key: "pat", label: "Paste a personal access token" });

    const pickedLabel = await pickOne(
      `  ${bold("How would you like to set GITHUB_TOKEN?")}`,
      choices.map((c) => c.label),
      0,
    );
    const choice = choices.find((c) => c.label === pickedLabel)?.key ?? "pat";

    if (choice === "squad") {
      githubToken = squadGhToken;
    } else if (choice === "host") {
      githubToken = hostGhToken;
    } else if (choice === "login") {
      console.log(
        dim(
          "\n  → starting gh auth login (writes to docker/data/gh/). Follow the prompts; complete the device code in your browser.\n",
        ),
      );
      const { token, user } = runGhAuthLoginSandboxed();
      if (token) {
        githubToken = token;
        const tag = user ? `@${user}` : mask(token);
        console.log(green(`  ✓ signed in as ${tag}`));
      } else {
        console.log(red("  ✗ gh auth login did not produce a token; skipping."));
      }
    } else {
      githubToken = await ask(
        `  ${bold("GITHUB_TOKEN")} ${dim("(create at github.com/settings/tokens)")}`,
        { default: existingEnv.GITHUB_TOKEN, secret: true },
      );
    }
    summary.push(
      githubToken ? "GitHub token set" : dim("GitHub token: (empty, skipping)"),
    );
  }

  // ── Step 7: SSH key for GitHub (optional) ───────────────────────────
  stepHeader(7, TOTAL, "SSH key for GitHub", false);
  console.log(
    dim(
      `  Generates an ed25519 keypair under docker/data/ssh/id_ed25519 that the container mounts. Used for \`git clone git@github.com:...\` and pushes.`,
    ),
  );
  const sshDir = join(DATA_DIR, "ssh");
  const sshKeyPath = join(sshDir, "id_ed25519");
  const sshExists = existsSync(sshKeyPath);
  if (await skipPrompt(sshExists)) {
    summary.push(sshExists ? "SSH key (existing)" : dim("SSH key: skipped"));
  } else {
    mkdirSync(sshDir, { recursive: true, mode: 0o700 });
    let overwrite = false;
    if (sshExists) {
      overwrite = await askYesNo(
        `  Key already exists at ${sshKeyPath}. Regenerate?`,
        false,
      );
    }
    if (!sshExists || overwrite) {
      if (overwrite) {
        try {
          execSync(`rm -f ${sshKeyPath} ${sshKeyPath}.pub`);
        } catch {
          // best effort
        }
      }
      try {
        execSync(
          `ssh-keygen -t ed25519 -f ${sshKeyPath} -N "" -C "squad-container" -q`,
          { stdio: ["ignore", "ignore", "pipe"] },
        );
        try {
          chmodSync(sshKeyPath, 0o600);
        } catch {
          // best-effort
        }
        console.log(green(`  ✓ generated ${sshKeyPath}`));
      } catch (err) {
        console.log(red(`  ✗ ssh-keygen failed: ${err.message}. Install ssh and re-run.`));
      }
    }
    if (existsSync(`${sshKeyPath}.pub`)) {
      const pub = readFileSync(`${sshKeyPath}.pub`, "utf8").trim();
      console.log(bold("\n  Public key — paste into GitHub → Settings → SSH keys:\n"));
      console.log("  " + pub);
      console.log(dim("\n  https://github.com/settings/ssh/new\n"));
      summary.push("SSH key ready");
    } else {
      summary.push(dim("SSH key: not generated"));
    }
  }

  // ── Step 8: Discord channel (optional) ──────────────────────────────
  stepHeader(8, TOTAL, "Discord channel", false);
  console.log(
    dim("  Wires up the Discord bot channel so a bot can mention @squad in your server."),
  );
  // Default to existing values — skipping this step must NOT blank them out.
  let discordBotToken = existingEnv.DISCORD_BOT_TOKEN ?? "";
  let discordWireToken = existingEnv.SQUAD_DISCORD_TOKEN ?? "";
  let wantDiscord = Boolean(discordBotToken);
  if (await skipPrompt(wantDiscord)) {
    summary.push(
      wantDiscord
        ? "Discord: kept existing"
        : dim("Discord: skipped"),
    );
  } else {
    wantDiscord = true;
    discordBotToken = await ask(
      `  ${bold("DISCORD_BOT_TOKEN")} ${dim("(from the Discord developer portal)")}`,
      { default: existingEnv.DISCORD_BOT_TOKEN, secret: true },
    );
    if (!discordWireToken) {
      discordWireToken = generateToken(24);
      console.log(dim(`  generated SQUAD_DISCORD_TOKEN (used between gateway and bot)`));
    }
    wantDiscord = Boolean(discordBotToken);
    summary.push(discordBotToken ? "Discord wired" : dim("Discord: (empty bot token)"));
  }

  // ── Write files ─────────────────────────────────────────────────────
  // Non-destructive merge: start from existing, only overwrite values the
  // wizard collected this run.
  const mergedEnv = { ...existingEnv, ...providerKeys };
  mergedEnv.SQUAD_PORT = String(Number(port) || 8080);
  mergedEnv.SQUAD_DASHBOARD_TOKEN = dashboardToken;
  mergedEnv.GIT_USER_NAME = gitUserName;
  mergedEnv.GIT_USER_EMAIL = gitUserEmail;
  mergedEnv.GITHUB_TOKEN = githubToken;
  // Discord values flow through whatever the step decided; if the user
  // skipped, those defaults are existingEnv values, not blanks.
  mergedEnv.DISCORD_BOT_TOKEN = discordBotToken;
  mergedEnv.SQUAD_DISCORD_TOKEN = discordWireToken;

  writeFileSync(ENV_PATH, renderEnv(mergedEnv));
  try {
    chmodSync(ENV_PATH, 0o600);
  } catch {
    // Best-effort on Windows.
  }

  const existingConfig = (() => {
    if (!existsSync(CONFIG_PATH)) return null;
    try {
      return JSON.parse(readFileSync(CONFIG_PATH, "utf8"));
    } catch {
      return null;
    }
  })();

  writeFileSync(
    CONFIG_PATH,
    renderConfig(existingConfig, {
      port: Number(port) || 8080,
      delivery,
      primaryModel,
      fallbacks,
      providers: configuredProviders,
      discord: wantDiscord && Boolean(discordBotToken),
    }),
  );

  // Seed the shared searxng settings.yml (once) so the compose sidecar has
  // JSON output enabled and a random secret_key on first boot.
  seedSearxngSettings();

  // Register this squad in ~/.squad/squads.json, set it as the current
  // squad, and regenerate ~/.squad/docker-compose.yml. The host port from
  // the wizard becomes the squad's host-side port mapping (container always
  // listens on 8080 internally).
  const hostPort = Number(port) || 8080;
  syncRegistryAndCompose(hostPort);

  console.log(`\n${bold("Summary")}`);
  for (const line of summary) console.log(`  • ${line}`);
  console.log("");
  console.log(green(`✓ wrote ${ENV_PATH}`));
  console.log(green(`✓ wrote ${CONFIG_PATH}`));
  console.log(green(`✓ wrote ${SEARXNG_SETTINGS}`));
  console.log(green(`✓ registered squad '${SQUAD_NAME}' on host port ${hostPort}`));

  console.log(`
${bold("Next steps")}

  ${green("Install CLI:")}  scripts/install.sh                  ${dim("# once; global 'squad' binary")}
  ${green("Start:")}        squad mgr start ${SQUAD_NAME}${" ".repeat(Math.max(0, 20 - SQUAD_NAME.length))}${dim("# docker compose up -d squad-" + SQUAD_NAME)}
  ${green("Chat:")}         squad repl                          ${dim("# or: squad chat 'hello'")}
  ${green("Dashboard:")}    http://localhost:${hostPort}/${" ".repeat(Math.max(0, 18 - String(hostPort).length))}${dim("# bearer token: " + ENV_PATH)}

  Add another squad: ${bold(`squad mgr create <name>`)} ${dim("(or re-run with --squad <name>)")}
  See all squads:    ${bold("squad mgr ls")}

Re-run ${bold("squad onboard")} (or ${bold("node scripts/setup.mjs --squad " + SQUAD_NAME)}) any time to fill in a skipped step or rotate a value.
`);
  rl.close();
}

main().catch((err) => {
  console.error(red(`\n✗ setup failed: ${err.message}`));
  rl.close();
  exit(1);
});
