#!/usr/bin/env node
// Interactive Squad setup wizard.
//
// Walks the user through the minimum config + secrets needed to launch the
// gateway, then writes them to ./docker/config.json and ./docker/.env. The
// docker/ folder is the single bind-mount surface the container reads — see
// docker-compose.yml.
//
// Re-runnable: detects existing files and offers to keep, overwrite, or merge
// individual values. No external deps so it works before `pnpm install`.

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin, stdout, argv, env, exit } from "node:process";
import { randomBytes } from "node:crypto";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, "..");
const DOCKER_DIR = join(REPO_ROOT, "docker");
const CONFIG_PATH = join(DOCKER_DIR, "config.json");
const ENV_PATH = join(DOCKER_DIR, ".env");
const DATA_DIR = join(DOCKER_DIR, "data");

const FORCE = argv.includes("--force") || argv.includes("-f");
const NON_INTERACTIVE = argv.includes("--yes") || argv.includes("-y");

const rl = createInterface({ input: stdin, output: stdout });

function bold(s) {
  return `\x1b[1m${s}\x1b[0m`;
}
function dim(s) {
  return `\x1b[2m${s}\x1b[0m`;
}
function green(s) {
  return `\x1b[32m${s}\x1b[0m`;
}
function yellow(s) {
  return `\x1b[33m${s}\x1b[0m`;
}
function red(s) {
  return `\x1b[31m${s}\x1b[0m`;
}

async function ask(prompt, { default: def, secret = false } = {}) {
  if (NON_INTERACTIVE) return def ?? "";
  const suffix = def ? dim(` [${secret ? mask(def) : def}]`) : "";
  const answer = (await rl.question(`${prompt}${suffix} `)).trim();
  return answer || def || "";
}

async function askChoice(prompt, choices, def) {
  if (NON_INTERACTIVE) return def;
  const labels = choices
    .map((c, i) => `${i + 1}) ${c}${c === def ? dim(" (default)") : ""}`)
    .join("  ");
  while (true) {
    const raw = (await rl.question(`${prompt}\n  ${labels}\n> `)).trim();
    if (!raw) return def;
    const n = Number(raw);
    if (Number.isInteger(n) && n >= 1 && n <= choices.length) return choices[n - 1];
    if (choices.includes(raw)) return raw;
    console.log(red("  pick a number from the list above"));
  }
}

async function askYesNo(prompt, def = false) {
  if (NON_INTERACTIVE) return def;
  const suffix = def ? "[Y/n]" : "[y/N]";
  while (true) {
    const raw = (await rl.question(`${prompt} ${suffix} `)).trim().toLowerCase();
    if (!raw) return def;
    if (["y", "yes"].includes(raw)) return true;
    if (["n", "no"].includes(raw)) return false;
    console.log(red("  please answer yes or no"));
  }
}

function mask(secret) {
  if (!secret) return "";
  if (secret.length <= 8) return "***";
  return `${secret.slice(0, 4)}…${secret.slice(-4)}`;
}

function generateToken(bytes = 32) {
  return randomBytes(bytes).toString("base64url");
}

// Minimal .env parser — KEY=VALUE per line, ignores comments and blanks.
function parseEnv(text) {
  const out = {};
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function loadEnvFile(path) {
  if (!existsSync(path)) return {};
  return parseEnv(readFileSync(path, "utf8"));
}

function renderEnv(values) {
  const lines = [
    "# Generated by scripts/setup.mjs — re-run `pnpm setup` to change.",
    "# This file holds secrets. It is gitignored. Do NOT commit it.",
    "",
    "# --- Required ---",
    `ANTHROPIC_API_KEY=${values.ANTHROPIC_API_KEY ?? ""}`,
    "",
    "# Bearer token for the dashboard + any first-party clients. Treat as a password.",
    `SQUAD_DASHBOARD_TOKEN=${values.SQUAD_DASHBOARD_TOKEN ?? ""}`,
    "",
    "# --- Optional LLM providers ---",
  ];
  for (const k of ["OPENAI_API_KEY", "OPENROUTER_API_KEY"]) {
    const v = values[k];
    lines.push(v ? `${k}=${v}` : `# ${k}=`);
  }
  lines.push("", "# --- Optional Discord channel ---");
  for (const k of ["DISCORD_BOT_TOKEN", "SQUAD_DISCORD_TOKEN"]) {
    const v = values[k];
    lines.push(v ? `${k}=${v}` : `# ${k}=`);
  }
  // Carry over any unknown keys the user added by hand.
  const known = new Set([
    "ANTHROPIC_API_KEY",
    "SQUAD_DASHBOARD_TOKEN",
    "OPENAI_API_KEY",
    "OPENROUTER_API_KEY",
    "DISCORD_BOT_TOKEN",
    "SQUAD_DISCORD_TOKEN",
  ]);
  const extras = Object.entries(values).filter(([k, v]) => !known.has(k) && v);
  if (extras.length) {
    lines.push("", "# --- Other ---");
    for (const [k, v] of extras) lines.push(`${k}=${v}`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderConfig(opts) {
  const providers = { anthropic: { api_key_env: "ANTHROPIC_API_KEY" } };
  if (opts.haveOpenai)     providers.openai     = { api_key_env: "OPENAI_API_KEY" };
  if (opts.haveOpenrouter) providers.openrouter = { api_key_env: "OPENROUTER_API_KEY" };

  const tokens = [
    { label: "dashboard", key_env: "SQUAD_DASHBOARD_TOKEN", scopes: ["*"] },
  ];
  if (opts.discord) {
    tokens.push({
      label: "discord-connector",
      key_env: "SQUAD_DISCORD_TOKEN",
      scopes: ["channel:discord", "chat.*", "session.*"],
    });
  }

  const channels = opts.discord
    ? { discord: { token_env: "DISCORD_BOT_TOKEN" } }
    : {};

  const cfg = {
    $comment: "Generated by scripts/setup.mjs — re-run `pnpm setup` to change. Safe to edit by hand; the wizard preserves unknown keys on re-run.",
    server: {
      host: "0.0.0.0",
      port: opts.port,
      data_dir: "./docker/data",
    },
    auth: { tokens },
    chat: { delivery: opts.delivery },
    llm: {
      primary: { model: opts.primaryModel },
      fallbacks: opts.fallbacks.map((m) => ({ model: m })),
      providers,
    },
    subagents: {
      max_concurrent_global: 8,
      max_concurrent_per_parent: 4,
      max_tree_depth: 3,
    },
    policy: {
      approvals: {
        default: "tag-match",
        require_for_tags: ["write", "exec", "network"],
        timeout_seconds: 120,
      },
    },
    plugins: [],
    channels,
  };

  return JSON.stringify(cfg, null, 2) + "\n";
}

async function main() {
  console.log(bold("\nSquad setup wizard\n"));
  console.log(
    `Writes ${dim("docker/config.json")} and ${dim("docker/.env")} — the bind-mounted state read by docker-compose and the local launcher.\n`,
  );

  if (!existsSync(DOCKER_DIR)) {
    mkdirSync(DOCKER_DIR, { recursive: true });
    console.log(green(`✓ created ${DOCKER_DIR}`));
  }
  if (!existsSync(DATA_DIR)) {
    mkdirSync(DATA_DIR, { recursive: true });
    console.log(green(`✓ created ${DATA_DIR}/ (sqlite + uploads land here)`));
  }

  const existingEnv = loadEnvFile(ENV_PATH);
  const configExists = existsSync(CONFIG_PATH);

  if ((Object.keys(existingEnv).length || configExists) && !FORCE) {
    console.log(
      yellow(
        `\nFound existing setup in docker/. Wizard will offer current values as defaults; press Enter to keep them, or pass --force to start clean.\n`,
      ),
    );
  }

  const anthropicKey = await ask(
    `${bold("Anthropic API key")} ${dim("(required — get one at console.anthropic.com)")}`,
    { default: env.ANTHROPIC_API_KEY || existingEnv.ANTHROPIC_API_KEY, secret: true },
  );
  if (!anthropicKey) {
    console.log(red("\n✗ ANTHROPIC_API_KEY is required. Aborting."));
    exit(1);
  }

  const haveOpenai = await askYesNo(
    `Add an OpenAI API key? ${dim("(optional, lets you use OpenAI models)")}`,
    Boolean(existingEnv.OPENAI_API_KEY),
  );
  const openaiKey = haveOpenai
    ? await ask("  OpenAI API key", { default: existingEnv.OPENAI_API_KEY, secret: true })
    : "";

  const haveOpenrouter = await askYesNo(
    `Add an OpenRouter API key? ${dim("(optional, opens up ~24 OpenAI-compatible providers)")}`,
    Boolean(existingEnv.OPENROUTER_API_KEY),
  );
  const openrouterKey = haveOpenrouter
    ? await ask("  OpenRouter API key", {
        default: existingEnv.OPENROUTER_API_KEY,
        secret: true,
      })
    : "";

  const wantDiscord = await askYesNo(
    `Wire up the Discord channel? ${dim("(optional)")}`,
    Boolean(existingEnv.DISCORD_BOT_TOKEN),
  );
  let discordBotToken = "";
  let discordWireToken = existingEnv.SQUAD_DISCORD_TOKEN || "";
  if (wantDiscord) {
    discordBotToken = await ask(
      `  Discord bot token ${dim("(from the Discord developer portal)")}`,
      { default: existingEnv.DISCORD_BOT_TOKEN, secret: true },
    );
    if (!discordWireToken) {
      discordWireToken = generateToken(24);
      console.log(dim(`  generated SQUAD_DISCORD_TOKEN (used between gateway and bot)`));
    }
  }

  const dashboardDefault =
    existingEnv.SQUAD_DASHBOARD_TOKEN && existingEnv.SQUAD_DASHBOARD_TOKEN !== "dev-dashboard-token"
      ? existingEnv.SQUAD_DASHBOARD_TOKEN
      : generateToken();
  const dashboardToken = await ask(
    `${bold("Dashboard auth token")} ${dim("(bearer for the web UI; default is freshly generated)")}`,
    { default: dashboardDefault, secret: true },
  );

  const port = await ask(`Port to expose ${dim("(default 8080)")}`, {
    default: env.SQUAD_PORT || "8080",
  });

  const delivery = await askChoice(
    `Chat delivery mode when a message arrives mid-run:`,
    ["interrupt", "queue"],
    "interrupt",
  );

  const primaryModel = await ask(`Primary model`, { default: "anthropic/claude-sonnet-4-5" });

  const fallbacksRaw = await ask(
    `Fallback models ${dim("(comma-separated, in order — leave blank for none)")}`,
    { default: openaiKey ? "openai/gpt-4o" : "" },
  );
  const fallbacks = fallbacksRaw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  // Write env.
  const mergedEnv = {
    ...existingEnv,
    ANTHROPIC_API_KEY: anthropicKey,
    SQUAD_DASHBOARD_TOKEN: dashboardToken,
    OPENAI_API_KEY: openaiKey,
    OPENROUTER_API_KEY: openrouterKey,
    DISCORD_BOT_TOKEN: discordBotToken,
    SQUAD_DISCORD_TOKEN: wantDiscord ? discordWireToken : "",
  };
  writeFileSync(ENV_PATH, renderEnv(mergedEnv));
  try {
    chmodSync(ENV_PATH, 0o600);
  } catch {
    // Best-effort on Windows.
  }
  console.log(green(`\n✓ wrote ${ENV_PATH}`));

  // Write config.
  writeFileSync(
    CONFIG_PATH,
    renderConfig({
      port: Number(port) || 8080,
      delivery,
      primaryModel,
      fallbacks,
      haveOpenai: Boolean(openaiKey),
      haveOpenrouter: Boolean(openrouterKey),
      discord: wantDiscord && Boolean(discordBotToken),
    }),
  );
  console.log(green(`✓ wrote ${CONFIG_PATH}`));

  console.log(`
${bold("Next steps")}

  ${green("Docker:")}    pnpm start:docker        ${dim("# build + up (foreground)")}
  ${green("Local:")}     pnpm start:local         ${dim("# install + build + run via node")}
  ${green("Dashboard:")} http://localhost:${port}/    ${dim("# bearer token: see docker/.env")}

Re-run ${bold("pnpm setup")} any time to add a provider, change ports, or rotate the dashboard token.
`);
  rl.close();
}

main().catch((err) => {
  console.error(red(`\n✗ setup failed: ${err.message}`));
  rl.close();
  exit(1);
});
