export const GOOGLE_CALENDAR_GUIDANCE = [
  "Google Calendar — list, create, update, delete, RSVP events on connected Google accounts.",
  "Operates against whichever connected account has the `calendar` feature enabled. If none is",
  "connected, every tool throws — call google_list_accounts / google_connect_url first.",
  "",
  "Tools in this group:",
  "  - google_calendar_list_calendars  → enumerate the user's calendars (id, summary, primary, role).",
  "  - google_calendar_list_events     → events in a time window; defaults to next 7 days on primary.",
  "  - google_calendar_create_event    → new event; ISO-8601 datetimes for timed, YYYY-MM-DD for all-day.",
  "  - google_calendar_update_event    → patch fields on an existing event id.",
  "  - google_calendar_delete_event    → remove an event by id.",
  "  - google_calendar_rsvp_event      → set the connected user's response to accepted/declined/tentative.",
  "",
  "Conventions:",
  "  - calendar_id defaults to 'primary' on every tool. Use list_calendars to discover others.",
  "  - send_updates controls attendee notifications: 'all' emails everyone, 'externalOnly' skips guests",
  "    on the same domain, 'none' is silent. Default is 'none' — be explicit when invitations matter.",
  "  - Free-text search is supported via the `query` argument on list_events.",
  "  - Event ids returned by list_events / create_event are stable; pass them through to update/delete/rsvp.",
  "",
  "Common patterns:",
  "  - 'what's on my calendar tomorrow':  list_events with from/to bracketing tomorrow.",
  "  - 'block 2-3pm for focus':           create_event with start/end ISO datetimes, no attendees.",
  "  - 'move my 4pm to 5pm':              update_event with new start/end on the existing event_id.",
  "  - 'decline the standup':             rsvp_event with response='declined'.",
].join("\n");
