export const GOOGLE_DRIVE_GUIDANCE = [
  "Google Drive — search, list folders, and read file contents on the connected Google account.",
  "Operates against the first connected account with the `drive` feature enabled. Use",
  "google_list_accounts to confirm an account is connected before calling these tools.",
  "",
  "Tools in this group:",
  "  - google_drive_search      → Drive query syntax (e.g. \"name contains 'budget' and mimeType = 'application/pdf'\").",
  "  - google_drive_list_files  → list contents of a folder by id (defaults to root).",
  "  - google_drive_read        → fetch file content by id; Google Docs/Sheets/Slides export to text/CSV.",
  "",
  "Conventions:",
  "  - File ids are stable Google strings — pass through from search/list_files into read.",
  "  - mimeType strings drive read behavior:",
  "      * application/vnd.google-apps.document      → exported as text/plain.",
  "      * application/vnd.google-apps.spreadsheet   → exported as text/csv.",
  "      * application/vnd.google-apps.presentation  → exported as text/plain.",
  "      * everything else                           → downloaded raw, base64 if binary.",
  "  - read defaults to a 64KB cap; raise via max_bytes when you need more.",
  "  - Trashed files are excluded from search by default; pass include_trashed=true to include them.",
  "",
  "Common patterns:",
  "  - 'find my Q3 plan doc':         google_drive_search query=\"name contains 'Q3 plan'\".",
  "  - 'list /Projects/2026':         resolve the folder id then google_drive_list_files folder_id=...",
  "  - 'read this CSV':               google_drive_read file_id=...; result is the raw CSV body.",
  "  - 'show me the slides':          google_drive_read file_id=... — slides export as plain text outline.",
].join("\n");
