export const DISCORD_GUIDANCE = [
  "Discord tools — read and write Discord through the bot wired into the channel-discord plugin.",
  "Channels, threads, messages, reactions, embeds, webhooks, and basic server/member/role lookups.",
  "",
  "Tools in this group:",
  "  - discord_message    → send / reply / edit / delete / bulk-delete / pin / unpin / fetch / send-embed / react / remove-reaction.",
  "  - discord_channel    → list / get / create / edit / delete channels and edit channel permission overwrites.",
  "  - discord_thread     → create / list / edit / delete / archive / unarchive / lock / unlock threads, manage thread members.",
  "  - discord_webhook    → create / list / post-via webhook in a channel.",
  "  - discord_server     → get-guild / get-member / list-roles.",
  "",
  "Each tool takes an `action` string plus the arguments for that action — picking the right tool",
  "narrows the schema the model has to consider. A discord thread is just a channel under the hood,",
  "so to read messages from a thread call discord_message with action=fetch_messages and the thread id.",
  "",
  "IDs are Discord snowflakes (numeric strings). The bot must already be a member of the guild and",
  "have the relevant permissions; failures bubble up as error strings rather than throwing.",
  "",
  "Common patterns:",
  "  - 'post in #ops':            discord_message action=send + channel_id.",
  "  - 'react with 👍':            discord_message action=react + channel_id + message_id + emoji.",
  "  - 'spin up a thread':        discord_thread action=create + channel_id + name (optionally message_id to thread off a message).",
  "  - 'create #release-notes':   discord_channel action=create + guild_id + name.",
  "  - 'post via webhook':        discord_webhook action=post + webhook_id + webhook_token + content.",
  "",
  "Custom emoji syntax for react / remove_reaction: name:id (e.g. partyparrot:823109283109283).",
  "Unicode emoji are passed through as-is.",
  "",
  "Routine delivery to Discord:",
  "  - Pass `delivery: { kind: \"discord\", extras: { channelId: \"<snowflake>\" } }` to",
  "    create_cron_job / update_cron_job. `guildId` is optional and goes alongside",
  "    `channelId` inside `extras`.",
  "  - The handler is registered by this plugin; if `discord` doesn't show up in",
  "    list_delivery_kinds, the plugin isn't loaded — fix that before scheduling.",
].join("\n");
